(function(){
  'use strict';
  var saving=false,requestInFlight=false,saveWatchdog=null,calendarSelectedStaff='';
  function editingId(){return typeof editingAppointmentId!=='undefined'?editingAppointmentId:null}
  function appointment(){var id=editingId();return id&&Array.isArray(window.appts)?window.appts.find(function(item){return String(item.id)===String(id)})||null:null}
  function closeSuggestions(){var panel=document.getElementById('typedCustomerSuggestions');if(panel){panel.classList.remove('show');panel.style.pointerEvents='none'}}
  function elements(){var modal=document.getElementById('appointmentModal'),form=modal&&modal.querySelector('form.sheet'),save=form&&form.querySelector('button.save:not(#permanentAppointmentDelete):not(#permanentAppointmentCancel):not(#directAppointmentDelete)');return {modal:modal,form:form,save:save}}
  function customerKey(value){return String(value||'').trim().toLocaleLowerCase('tr').replace(/[ç]/g,'c').replace(/[ğ]/g,'g').replace(/[ıi]/g,'i').replace(/[ö]/g,'o').replace(/[ş]/g,'s').replace(/[ü]/g,'u').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
  function clientList(){try{return Array.isArray(remoteClients)?remoteClients:[]}catch(error){return []}}
  function enforceCalendarStaff(){if(editingId()||!calendarSelectedStaff)return;var select=document.getElementById('appointmentStaff');if(select&&Array.from(select.options).some(function(option){return option.value===calendarSelectedStaff}))select.value=calendarSelectedStaff}
  function fillCustomer(client){if(!client)return;var input=document.getElementById('appointmentCustomer'),phone=document.getElementById('appointmentPhone');if(input)input.value=String(client.full_name||'');if(phone)phone.value=String(client.phone||'').trim();try{if(typeof applyCustomerHistory==='function')applyCustomerHistory(client)}catch(error){}enforceCalendarStaff();closeSuggestions()}
  function renderCustomerPicker(){var input=document.getElementById('appointmentCustomer'),panel=document.getElementById('typedCustomerSuggestions');if(!input||!panel)return;var term=customerKey(input.value);if(!term){panel.innerHTML='';panel.classList.remove('show');panel.style.pointerEvents='none';return}var matches=clientList().filter(function(client){return customerKey(client.full_name).includes(term)}).slice(0,8);panel.innerHTML=matches.map(function(client){var name=String(client.full_name||''),phone=String(client.phone||'');return '<button type="button" data-salon-client-id="'+String(client.id).replace(/"/g,'&quot;')+'"><strong>'+name.replace(/&/g,'&amp;').replace(/</g,'&lt;')+'</strong><small style="display:block">'+phone.replace(/&/g,'&amp;').replace(/</g,'&lt;')+'</small></button>'}).join('');panel.classList.toggle('show',matches.length>0);panel.style.pointerEvents=matches.length?'auto':'none'}
  function bindCustomerPicker(){var input=document.getElementById('appointmentCustomer'),panel=document.getElementById('typedCustomerSuggestions');if(!input||!panel)return;input.removeAttribute('list');input.oninput=renderCustomerPicker;input.onfocus=renderCustomerPicker;function pick(event){var button=event.target&&event.target.closest&&event.target.closest('button[data-salon-client-id]');if(!button)return;event.preventDefault();event.stopImmediatePropagation();var client=clientList().find(function(item){return String(item.id)===String(button.getAttribute('data-salon-client-id'))});fillCustomer(client)}panel.onpointerdown=pick;panel.ontouchstart=pick;panel.onmousedown=pick;panel.onclick=pick}
  async function saveNow(event){event&&event.preventDefault();event&&event.stopPropagation();var parts=elements(),form=parts.form,button=parts.save;if(!form||saving||requestInFlight)return false;enforceCalendarStaff();if(form.reportValidity&&!form.reportValidity())return false;saving=true;var label=button&&button.textContent||'Randevuyu kaydet';if(button){button.disabled=true;button.textContent='Kaydediliyor…'}closeSuggestions();saveWatchdog=setTimeout(function(){if(!saving)return;saving=false;if(button&&document.body.contains(button)){button.disabled=false;button.textContent=label}window.showAppToast&&window.showAppToast('Kayıt beklenenden uzun sürdü','Ekran serbest bırakıldı. İnternet bağlantısını kontrol edip tekrar deneyebilirsiniz.')},12000);try{if(typeof window.saveAppointment!=='function')throw new Error('Randevu kayıt işlevi yüklenemedi.');var task=Promise.resolve(window.saveAppointment({preventDefault:function(){},stopPropagation:function(){},target:form,currentTarget:form,submitter:button}));requestInFlight=true;task.then(function(){requestInFlight=false},function(){requestInFlight=false});var outcome=await Promise.race([task.then(function(){return 'done'}),new Promise(function(resolve){setTimeout(function(){resolve('timeout')},10000)})]);if(outcome==='timeout'){window.closeAppointmentModal&&window.closeAppointmentModal();if(typeof window.showPage==='function')window.showPage('calendar');window.showAppToast&&window.showAppToast('İşlem sunucuya gönderildi','Takvim arka planda doğrulanıyor. Ekran kilitlenmedi.');task.catch(function(error){console.warn('[appointment-actions] late save failed',error)}).finally(function(){Promise.resolve(window.reloadRemoteData&&window.reloadRemoteData()).catch(function(error){console.warn('[appointment-actions] refresh failed',error)})})}}catch(error){console.error('[appointment-actions] save',error);window.showAppToast&&window.showAppToast('Randevu kaydedilemedi',error&&error.message||'Tekrar deneyin.')}finally{if(saveWatchdog){clearTimeout(saveWatchdog);saveWatchdog=null}saving=false;if(button&&document.body.contains(button)){button.disabled=false;button.textContent=label}}return false}
  function cancelNow(event){event&&event.preventDefault();event&&event.stopPropagation();if(saveWatchdog){clearTimeout(saveWatchdog);saveWatchdog=null}saving=false;calendarSelectedStaff='';var parts=elements();if(parts.save){parts.save.disabled=false;parts.save.textContent='Randevuyu kaydet'}closeSuggestions();if(typeof window.closeAppointmentModal==='function')window.closeAppointmentModal();else document.getElementById('appointmentModal')?.classList.remove('show');return false}
  function deleteNow(event){event&&event.preventDefault();event&&event.stopPropagation();closeSuggestions();var id=editingId();if(id&&typeof window.requestAppointmentDeletion==='function')window.requestAppointmentDeletion(id);else window.showAppToast&&window.showAppToast('Silme açılamadı','Randevuyu takvimden yeniden açın.');return false}
  function shareNow(event){event&&event.preventDefault();event&&event.stopPropagation();closeSuggestions();var item=appointment();if(item&&typeof window.shareAppointmentWhatsApp==='function')window.shareAppointmentWhatsApp(item.id);return false}
  function bind(){var parts=elements(),form=parts.form,save=parts.save;if(!form)return;form.style.position='relative';form.style.zIndex='1';form.onsubmit=saveNow;if(save){save.type='button';save.disabled=false;save.onclick=saveNow;save.ontouchend=null;save.dataset.appointmentAction='save'}var back=Array.from(form.querySelectorAll('button.back')).find(function(button){return button.textContent.trim()==='Vazgeç'});if(back){back.type='button';back.onclick=cancelNow;back.ontouchend=null;back.dataset.appointmentAction='back'}var remove=document.getElementById('permanentAppointmentDelete');if(remove){remove.type='button';remove.onclick=deleteNow;remove.ontouchend=null;remove.dataset.appointmentAction='delete'}var share=document.getElementById('shareAppointmentWhatsapp');if(share){share.type='button';share.onclick=shareNow;share.ontouchend=null;share.dataset.appointmentAction='share'}closeSuggestions();bindCustomerPicker();enforceCalendarStaff()}
  var style=document.createElement('style');style.id='appointmentFormActionStyle231';style.textContent='#appointmentModal.show{pointer-events:auto!important}#appointmentModal form.sheet{position:relative!important;z-index:1!important;pointer-events:auto!important}#appointmentModal form.sheet>button{position:relative!important;z-index:1305!important;pointer-events:auto!important;touch-action:manipulation!important;-webkit-tap-highlight-color:transparent}#appointmentModal .customer-suggestions:not(.show){display:none!important;pointer-events:none!important}';document.head.appendChild(style);
  window.bindAppointmentFormActions=bind;window.runAppointmentFormSave=saveNow;
  var previousOpen=window.openAppointmentModal;if(typeof previousOpen==='function')window.openAppointmentModal=function(){var id=arguments[1],staffName=arguments[2];calendarSelectedStaff=!id&&staffName?String(staffName):'';var result=previousOpen.apply(this,arguments);bind();setTimeout(function(){enforceCalendarStaff();bind()},0);return result};
  bind();var modal=document.getElementById('appointmentModal');if(modal){var wasOpen=modal.classList.contains('show');new MutationObserver(function(){var isOpen=modal.classList.contains('show');if(isOpen&&!wasOpen)setTimeout(bind,0);if(!isOpen&&wasOpen)calendarSelectedStaff='';wasOpen=isOpen}).observe(modal,{attributes:true,attributeFilter:['class']})}
})();

// Extend the existing calendar movement path. No writes happen during gestures.
(function(){
  'use strict';
  var gesture=null,highlight=null,frame=0,moving=false,suppressClickUntil=0;
  function item(id){return appts.find(function(row){return String(row.id)===String(id)})}
  function allowed(row){return row&&currentUser&&(currentUser.role==='yonetici'||String(row.employeeId)===String(currentUser.id))}
  function targetAt(x,y){return document.elementsFromPoint(x,y).map(function(node){return node.closest&&node.closest('[data-calendar-time][data-calendar-staff]')}).find(Boolean)}
  function mark(cell){if(highlight)highlight.classList.remove('drag-over');highlight=cell;if(cell){cell.classList.add('drag-over');cell.setAttribute('aria-label',cell.dataset.calendarStaff+' '+cell.dataset.calendarTime)}}
  function clear(){if(gesture&&gesture.timer)clearTimeout(gesture.timer);if(gesture&&gesture.card)gesture.card.classList.remove('calendar-dragging');gesture=null;window.salonCalendarDragging=false;mark(null);if(frame)cancelAnimationFrame(frame);frame=0}
  function scrollTick(){if(!gesture||!gesture.active)return;var y=gesture.y,edge=55,delta=y<edge?-8:y>innerHeight-edge?8:0;if(delta){var node=gesture.card.parentElement;while(node&&node!==document.body&&!(node.scrollHeight>node.clientHeight&&/auto|scroll/.test(getComputedStyle(node).overflowY)))node=node.parentElement;if(node&&node!==document.body)node.scrollTop+=delta;else window.scrollBy(0,delta);mark(targetAt(gesture.x,gesture.y))}frame=requestAnimationFrame(scrollTick)}
  async function moveConfirmed(id,date,time,staffName){if(moving)return;var row=item(id),employee=profileForEmployeeName(staffName);if(!allowed(row)||!employee||(currentUser.role!=='yonetici'&&String(employee.id)!==String(currentUser.id)))return;
    if(closedSlotFor(date,time,row.duration||60,employee.id)){showAppToast('Kapalı saat','Seçilen aralık kapalı.');return}
    if(appointmentOverlaps(date,time,row.duration||60,employee.id,id).length){showAppToast('Bu saat dolu','Seçilen aralık dolu.');return}
    moving=true;try{var result=await salonDb.from('appointments').update({scheduled_at:remoteSchedule(date,time),employee_id:employee.id}).eq('id',id).select('id');if(result.error)throw result.error;if(!result.data||result.data.length!==1)throw new Error('Randevu kaydı doğrulanamadı.');var url=row.phone&&appointmentUpdateNeedsWhatsApp(row,employee.id,date,time,staffName)?whatsappAppointmentUpdateUrl(row.customer,row.phone,date,time,staffName,row.amount,row.operation):'';await reloadRemoteData();showAppToast('Randevu taşındı',date+' '+time+' · '+staffName);if(url)window.location.href=url}catch(error){showAppToast('Taşınamadı',error.message||'Tekrar deneyin.')}finally{moving=false}}
  function requestMove(id,cell){var row=item(id);if(!allowed(row)||!cell||moving)return;var time=cell.dataset.calendarTime,staffName=cell.dataset.calendarStaff,date=selectedTeamDate(),employee=profileForEmployeeName(staffName);if(!employee||(currentUser.role!=='yonetici'&&String(employee.id)!==String(currentUser.id)))return;
    if(date===appointmentDate(row)&&time===row.time&&String(employee.id)===String(row.employeeId))return;
    if(closedSlotFor(date,time,row.duration||60,employee.id)){showAppToast('Kapalı saat','Seçilen aralık kapalı.');return}
    var conflicts=appointmentOverlaps(date,time,row.duration||60,employee.id,id),text=row.customer+' · '+row.operation+'\n'+row.staff+' · '+appointmentDate(row)+' '+row.time+'\n→ '+staffName+' · '+date+' '+time+(conflicts.length?'\n\n'+appointmentOverlapText(conflicts):'');
    if(conflicts.length){showAppToast('Bu saat dolu',appointmentOverlapText(conflicts));return}appointmentActionConfirm('Taşı',text,function(){moveConfirmed(id,date,time,staffName)});
  }
  window.startMove=function(event,id){if(!allowed(item(id))){event.preventDefault();return}clear();gesture={id:id,card:event.currentTarget,x:event.clientX,y:event.clientY,active:true,desktop:true};window.salonCalendarDragging=true;frame=requestAnimationFrame(scrollTick);event.dataTransfer.setData('text/plain',id);event.dataTransfer.effectAllowed='move'};
  window.allowTimeDrop=function(event){if(!currentUser)return;event.preventDefault();mark(event.currentTarget)};
  window.leaveTimeDrop=function(){mark(null)};
  window.dropInTeamCalendar=function(event,time,staffName){event.preventDefault();event.stopPropagation();var id=event.dataTransfer.getData('text/plain'),cell=event.currentTarget;clear();requestMove(id,cell)};
  var content=document.getElementById('calendarContent');if(!content)return;
  content.addEventListener('click',function(event){if(Date.now()<suppressClickUntil){event.preventDefault();event.stopImmediatePropagation()}},true);
  content.addEventListener('touchstart',function(event){if(event.touches.length!==1)return;var card=event.target.closest('[data-appointment-id]'),point=event.touches[0];if(!card||!allowed(item(card.dataset.appointmentId)))return;clear();gesture={id:card.dataset.appointmentId,card:card,startX:point.clientX,startY:point.clientY,x:point.clientX,y:point.clientY,active:false};gesture.timer=setTimeout(function(){if(!gesture)return;gesture.active=true;window.salonCalendarDragging=true;gesture.card.classList.add('calendar-dragging');frame=requestAnimationFrame(scrollTick)},400)}, {capture:true,passive:true});
  content.addEventListener('touchmove',function(event){if(!gesture)return;var point=event.touches[0];if(!point){clear();return}gesture.x=point.clientX;gesture.y=point.clientY;if(!gesture.active){if(Math.hypot(point.clientX-gesture.startX,point.clientY-gesture.startY)>8)clear();return}event.preventDefault();event.stopImmediatePropagation();mark(targetAt(point.clientX,point.clientY))},{capture:true,passive:false});
  content.addEventListener('touchend',function(event){if(!gesture)return;var id=gesture.id,active=gesture.active,cell=highlight;if(active){event.preventDefault();event.stopImmediatePropagation();suppressClickUntil=Date.now()+600}clear();if(active)requestMove(id,cell)},{capture:true,passive:false});
  content.addEventListener('touchcancel',clear,{capture:true,passive:true});
  content.addEventListener('dragover',function(event){if(!gesture||!gesture.desktop)return;gesture.x=event.clientX;gesture.y=event.clientY});
  content.addEventListener('dragend',clear);
  var style=document.createElement('style');style.textContent='.duration-cell.drag-over{background:#b8d8c9!important;outline:2px solid #187657!important;z-index:6!important}.calendar-dragging{outline:2px solid #187657!important;opacity:.8}.duration-cell:not(.hour-start){box-shadow:none}';document.head.append(style);
})();
