(function(){
'use strict';
var busy=false;
function isManager(){return typeof currentUser!=='undefined'&&currentUser&&currentUser.role==='yonetici'}
function toast(title,body){if(typeof showAppToast==='function')showAppToast(title,body)}
function fitCalendar(){var grid=document.querySelector('#calendarContent .duration-hour-grid');if(!grid)return;var columns=Math.max(1,grid.querySelectorAll(':scope > .team-head').length-1),cells=grid.querySelectorAll(':scope > .duration-cell').length,slots=Math.max(1,parseInt(grid.querySelector(':scope > .duration-end')?.style.gridRow,10)-2);grid.style.setProperty('grid-template-rows','auto repeat('+slots+',minmax(8px,1fr)) 0px','important');var endLabel=grid.querySelector(':scope > .duration-end');if(endLabel){endLabel.textContent='';endLabel.setAttribute('aria-label','Takvim sonu')}var hint=document.querySelector('#calendarContent .calendar-hint');if(hint)hint.textContent=hint.textContent.replace(/Takvim (.+?)–\d{2}\.\d{2} arasını gösterir\. Online kapanış (\d{2}\.\d{2});/,'Takvim $1–$2 ayarını kullanır;')}
function removeAdminFromStaff(){if(typeof staff==='undefined'||!Array.isArray(staff))return;staff=staff.filter(function(member){return member[0]!=='Salon Modern'})}
function installAdminProfileFilters(){if(window.__salonAdminProfileFiltersInstalled)return;window.__salonAdminProfileFiltersInstalled=true;['phase2OccupancyCards','phase2RenderEmployeePerformance','employeeFrom','visibleProfiles'].forEach(function(name){var original=window[name];if(typeof original!=='function')return;window[name]=function(){var profiles=window.remoteProfiles;window.remoteProfiles=(profiles||[]).filter(function(profile){return profile.username!=='salon.modern'});try{return original.apply(this,arguments)}finally{window.remoteProfiles=profiles}}});if(typeof renderHomeSummary==='function')renderHomeSummary()}
function enableEditableAppointmentAmount(){
  var amount=document.getElementById('appointmentAmount');if(!amount)return;
  amount.readOnly=false;amount.disabled=false;amount.step='0.01';amount.inputMode='decimal';
  amount.setAttribute('aria-describedby','appointmentAmountHint');
  if(!amount.dataset.manualPriceBound){
    amount.dataset.manualPriceBound='1';
    amount.addEventListener('input',function(){amount.dataset.manuallyEdited='true'});
  }
  var field=amount.closest('.field'),hint=document.getElementById('appointmentAmountHint');
  if(field&&!hint){hint=document.createElement('small');hint.id='appointmentAmountHint';hint.className='appointment-amount-hint';hint.textContent='Hizmet fiyatı otomatik gelir; bu randevu için değiştirebilirsiniz.';field.appendChild(hint)}
}
async function install(){if(!isManager()||!window.salonDb)return;removeAdminFromStaff();installAdminProfileFilters();var controls=document.getElementById('adminControls');if(!controls)return;var card=document.getElementById('bookingGlobalSettings');if(!card){card=document.createElement('div');card.id='bookingGlobalSettings';var schedule=document.getElementById('bookingScheduleAdmin');if(schedule)controls.insertBefore(card,schedule);else controls.prepend(card)}var result=await salonDb.from('booking_settings').select('online_booking_enabled,default_open_time,default_close_time').eq('id',true).maybeSingle();if(result.error){card.innerHTML='<div class="security">Online randevu ayarları alınamadı.</div>';return}var row=result.data||{},open=String(row.default_open_time||'09:00').slice(0,5),close=String(row.default_close_time||'19:00').slice(0,5);card.innerHTML='<div class="section"><h2>Genel çalışma saatleri</h2><span class="role">YÖNETİM</span></div><div class="booking-global-card"><label class="booking-online-switch"><input id="bookingOnlineEnabled" type="checkbox"'+(row.online_booking_enabled!==false?' checked':'')+'><span><strong>Online randevu sürekli açık</strong><small>Kapatıp kaydettiğinizde müşterilere hiçbir randevu saati sunulmaz.</small></span></label><div class="booking-global-times"><label class="field">Normal açılış<input id="bookingDefaultOpen" type="time" step="1800" value="'+open+'"></label><label class="field">Normal kapanış<input id="bookingDefaultClose" type="time" step="1800" value="'+close+'"></label></div><button type="button" class="save" id="bookingGlobalSave">Genel ayarları kaydet</button></div>';document.getElementById('bookingGlobalSave').onclick=save}
async function save(){if(!isManager()||busy)return;var button=document.getElementById('bookingGlobalSave'),enabled=document.getElementById('bookingOnlineEnabled').checked,open=document.getElementById('bookingDefaultOpen').value,close=document.getElementById('bookingDefaultClose').value,openMinute=Number(open.split(':')[1]),closeMinute=Number(close.split(':')[1]);if(!open||!close||close<=open||openMinute%30!==0||closeMinute%30!==0){toast('Saatleri kontrol edin','Saatleri yalnız tam veya yarım saat olarak seçin.');return}busy=true;button.disabled=true;button.textContent='Kaydediliyor…';try{var result=await salonDb.from('booking_settings').update({online_booking_enabled:enabled,default_open_time:open,default_close_time:close,updated_at:new Date().toISOString(),updated_by:currentUser.id}).eq('id',true).select('id').single();if(result.error)throw result.error;toast(enabled?'Online randevu açık':'Online randevu kapalı',enabled?open+'–'+close+' saatleri takvim ve online randevuya uygulandı.':'Müşteri ekranında saat sunulmayacak.');if(typeof reloadRemoteData==='function')await reloadRemoteData();else if(typeof renderCalendar==='function')renderCalendar()}catch(error){toast('Ayarlar kaydedilemedi',error.message||'Tekrar deneyin.')}finally{busy=false;if(button){button.disabled=false;button.textContent='Genel ayarları kaydet'}}}
function updateCurrentTimeLine(){
var grid=document.querySelector('#calendarContent .duration-hour-grid');if(!grid)return;
grid.querySelectorAll('.current-time-line').forEach(function(line){line.remove()});
var now=new Date(),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now),values={};parts.forEach(function(part){values[part.type]=part.value});
var today=values.year+'-'+values.month+'-'+values.day;
if(typeof selectedTeamDate!=='function'||selectedTeamDate()!==today||teamCalendarMode==='month')return;
var minute=Number(values.hour)*60+Number(values.minute),cells=Array.from(grid.querySelectorAll('[data-calendar-time]')),cell=cells.find(function(item){var time=item.dataset.calendarTime.split(':'),start=Number(time[0])*60+Number(time[1]);return minute>=start&&minute<start+30});if(!cell)return;
var time=cell.dataset.calendarTime.split(':'),fraction=(minute-Number(time[0])*60-Number(time[1]))/30,line=document.createElement('div');line.className='current-time-line';line.setAttribute('aria-label','Şu an '+values.hour+':'+values.minute);line.style.cssText='grid-column:2 / -1;grid-row:'+cell.style.gridRow+';align-self:start;transform:translateY('+(cell.getBoundingClientRect().height*fraction)+'px);border-top:2px solid #d1594f;z-index:30;pointer-events:none';grid.appendChild(line);
if(typeof syncCurrentTimeLineVisibility==='function')syncCurrentTimeLineVisibility();
}
var previousRender=window.renderCalendar;window.renderCalendar=function(){removeAdminFromStaff();var result=previousRender.apply(this,arguments);fitCalendar();requestAnimationFrame(function(){fitCalendar();updateCurrentTimeLine()});return result};
setInterval(updateCurrentTimeLine,60000);
window.addEventListener('resize',updateCurrentTimeLine);
document.addEventListener('visibilitychange',function(){if(!document.hidden)updateCurrentTimeLine()});
var previousOpenAppointment=window.openAppointmentModal;if(previousOpenAppointment)window.openAppointmentModal=function(){var result=previousOpenAppointment.apply(this,arguments),amount=document.getElementById('appointmentAmount'),modal=document.getElementById('appointmentModal'),editing=Boolean(arguments[1]);enableEditableAppointmentAmount();if(amount)amount.dataset.manuallyEdited='false';if(modal)modal.classList.toggle('appointment-editing',editing);return result};
var previousReload=window.reloadRemoteData;if(previousReload)window.reloadRemoteData=async function(){var result=await previousReload.apply(this,arguments);removeAdminFromStaff();await install();if(typeof renderCalendar==='function')renderCalendar();return result};
var previousShow=window.showPage;window.showPage=function(id){var result=previousShow.apply(this,arguments);if(id==='admin')install();if(id==='calendar')fitCalendar();return result};
var style=document.createElement('style');style.textContent='.booking-global-card{padding:15px;border:1px solid var(--line);border-radius:16px;background:#fff;margin-bottom:18px}.booking-online-switch{display:flex;gap:10px;align-items:flex-start;margin-bottom:12px}.booking-online-switch input{width:21px;height:21px;flex:none}.booking-online-switch strong,.booking-online-switch small{display:block}.booking-online-switch small{color:var(--muted);margin-top:3px}.booking-global-times{display:grid;grid-template-columns:1fr 1fr;gap:10px}#calendar .team-calendar.duration-hour-grid{height:calc(100svh - 220px)!important;min-height:570px!important;max-height:none!important}#calendar .team-calendar.duration-hour-grid>.duration-end,#calendar .team-calendar.duration-hour-grid>.duration-end-cell{height:0!important;min-height:0!important;border-top:0!important;overflow:hidden!important}#appointmentModal{overflow:hidden!important}#appointmentModal .sheet{max-height:calc(100svh - env(safe-area-inset-top) - 8px)!important;overflow-y:auto!important;overscroll-behavior:contain;padding-bottom:max(14px,env(safe-area-inset-bottom))!important}#appointmentModal.appointment-editing #appointmentRecurrence{display:none!important}@media(max-width:600px){#appointmentModal .sheet{padding:14px 16px!important}#appointmentModal .sheet h2{font-size:23px!important;line-height:1.12!important;margin:0 0 8px!important}#appointmentModal .field{margin:6px 0 3px!important;font-size:11px!important}#appointmentModal .field input,#appointmentModal .field select{min-height:42px!important;padding:8px 10px!important}#appointmentModal .row{gap:8px!important}#appointmentModal .date-caption{margin-top:2px!important}#appointmentModal .appointment-debt-warning{margin-top:7px!important;padding:8px 10px!important}#appointmentModal .debt-check{margin-top:7px!important;padding:8px 10px!important}#appointmentModal .save{margin-top:9px!important;padding:11px!important}#appointmentModal .back{margin-top:8px!important}#appointmentModal #shareAppointmentWhatsapp{margin-top:8px!important}}';document.head.appendChild(style);setTimeout(async function(){await install();if(typeof renderCalendar==='function')renderCalendar();fitCalendar()},0);
})();
