(function(){
'use strict';
var settings={default_open_time:'09:00:00',default_close_time:'19:00:00'},overrides={};
function hh(v){return String(v||'').slice(0,5)}
function minutes(v){var p=hh(v).split(':').map(Number);return p[0]*60+p[1]}
function timesFor(date,step){var o=overrides[date],closed=o&&o.is_closed,start=minutes(o&&!closed?o.open_time:settings.default_open_time),end=minutes(o&&!closed?o.close_time:settings.default_close_time),out=[];if(closed)return out;step=step||60;for(var m=start;m<=end;m+=step)out.push(String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0'));return out}
async function load(){if(!window.salonDb)return;var a=await window.salonDb.from('booking_settings').select('*').eq('id',true).maybeSingle(),b=await window.salonDb.from('booking_schedule_overrides').select('*');if(a.data)settings=a.data;overrides={};(b.data||[]).forEach(function(x){overrides[x.schedule_date]=x});window.SalonBookingSchedule={settings:settings,overrides:overrides,timesFor:timesFor};patch();if(typeof window.renderCalendar==='function')window.renderCalendar()}
function patch(){if(window.__salonSchedulePatched)return;window.__salonSchedulePatched=true;var oldSchedule=window.scheduleTimes;window.scheduleTimes=function(){var date=typeof window.selectedTeamDate==='function'?window.selectedTeamDate():new Date().toISOString().slice(0,10),list=timesFor(date,60);return list.length?list:(overrides[date]&&overrides[date].is_closed?[]:(oldSchedule?oldSchedule():[]))};var oldRender=window.renderCalendar;window.renderCalendar=function(){var result=oldRender.apply(this,arguments),date=typeof window.selectedTeamDate==='function'?window.selectedTeamDate():'';setTimeout(function(){var target=document.getElementById('calendarContent'),o=overrides[date];if(target&&o&&o.is_closed&&(!target.querySelector('.booking-day-closed'))){var note=document.createElement('div');note.className='empty booking-day-closed';note.textContent='Bu tarih çalışma dışı olarak ayarlanmıştır.';target.prepend(note)}},0);return result};var oldOpen=window.openTeamSlot;window.openTeamSlot=function(time,staffName){var date=typeof window.selectedTeamDate==='function'?window.selectedTeamDate():'',o=overrides[date];if(o&&o.is_closed){if(window.showAppToast)window.showAppToast('Salon kapalı','Bu tarih çalışma dışı olarak ayarlanmıştır.');return}return oldOpen.apply(this,arguments)}}
var oldReload=window.reloadRemoteData;if(oldReload)window.reloadRemoteData=async function(){var r=await oldReload.apply(this,arguments);await load();return r};setTimeout(load,0);
})();
