(function(){
'use strict';
var API='https://oxuwwjsakhcqimjsfris.supabase.co/functions/v1/customer-booking-request',rows=[],busy=new Set(),channel=null;
function manager(){return window.currentUser&&window.currentUser.role==='yonetici'}
function esc(value){return typeof window.safe==='function'?window.safe(String(value||'')):String(value||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function toast(a,b){if(typeof window.showAppToast==='function')window.showAppToast(a,b)}
function fmt(iso){try{return new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Istanbul',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}).format(new Date(iso))}catch(_){return iso}}
async function token(){var result=await window.salonDb.auth.getSession();return result.data&&result.data.session&&result.data.session.access_token||''}
async function call(action,options){options=options||{};var response=await fetch(API+'?action='+encodeURIComponent(action),Object.assign({},options,{headers:Object.assign({'Authorization':'Bearer '+await token(),'Content-Type':'application/json'},options.headers||{})})),data=await response.json().catch(function(){return {}});if(!response.ok)throw new Error(data.error||'İşlem tamamlanamadı.');return data}
function ensure(){
  if(document.getElementById('bookingRequests'))return;
  var app=document.getElementById('app'),nav=app&&app.querySelector('.nav'),page=document.createElement('section');page.id='bookingRequests';page.className='page';page.innerHTML='<div class="content"><button class="back" onclick="showPage(\'home\')">‹ Ana sayfa</button><div class="section"><h1 class="page-title">Randevu Talepleri</h1><span class="role" id="bookingRequestCount">0</span></div><div class="booking-request-tabs"><button class="active" data-filter="pending">Bekleyen</button><button data-filter="approved">Onaylanan</button><button data-filter="rejected">Reddedilen</button></div><div id="bookingRequestList"><div class="empty">Talepler yükleniyor…</div></div></div>';
  if(nav)app.insertBefore(page,nav);else app.appendChild(page);
  var style=document.createElement('style');style.textContent='.booking-request-tabs{display:flex;gap:6px;background:#eee9df;padding:4px;border-radius:12px;margin-bottom:14px}.booking-request-tabs button{flex:1;border:0;border-radius:9px;padding:9px 4px;background:transparent;color:var(--muted);font:600 12px inherit}.booking-request-tabs button.active{background:var(--paper);color:var(--ink)}.booking-request-card{background:var(--paper);border-radius:16px;padding:15px;margin-bottom:12px;border-left:4px solid var(--gold)}.booking-request-card.resolved{border-left-color:#82928c}.booking-request-card h3{margin:0 0 5px}.booking-request-card p{margin:4px 0;color:var(--muted);font-size:12px}.booking-request-card .request-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.booking-request-card select{width:100%;border:1px solid var(--line);border-radius:10px;padding:10px;background:white;margin-top:9px}.booking-request-card .request-actions button{border:0;border-radius:10px;padding:11px;font:600 13px inherit;background:var(--dark);color:white}.booking-request-card .request-actions .reject{background:#fff0ee;color:#a9514d}.booking-request-card .request-actions .whatsapp{background:#e8f3ed;color:#28634f}.pending-conflict{color:#a9514d!important;font-weight:700}';document.head.appendChild(style);
  var drawer=document.querySelector('#drawerLayer .drawer');if(drawer&&!document.getElementById('drawerBookingRequests')){var button=document.createElement('button');button.id='drawerBookingRequests';button.className='menu-item manager-menu';button.innerHTML='◷ &nbsp; Randevu Talepleri <b id="drawerBookingRequestBadge" style="float:right"></b>';button.onclick=function(){window.drawerPage('bookingRequests')};var admin=document.querySelector("[onclick=\"drawerPage('admin')\"]");drawer.insertBefore(button,admin||null)}
  page.querySelector('.booking-request-tabs').onclick=function(event){var button=event.target.closest('button');if(!button)return;page.querySelectorAll('.booking-request-tabs button').forEach(function(item){item.classList.toggle('active',item===button)});render(button.dataset.filter)};
}
function installPublicLink(){var card=document.querySelector('#auth .login-card')||document.querySelector('.auth .login-card');if(!card||document.getElementById('publicBookingLink'))return;var link=document.createElement('a');link.id='publicBookingLink';link.href='randevu/';link.textContent='Randevu Al';link.style.cssText='display:block;text-align:center;margin-top:16px;color:#a36e29;font-weight:700;text-decoration:none';card.appendChild(link)}
function currentFilter(){return document.querySelector('#bookingRequests .booking-request-tabs button.active')?.dataset.filter||'pending'}
function conflictCount(row){return rows.filter(function(other){return other.status==='pending'&&other.id!==row.id&&other.requested_start_at===row.requested_start_at&&(other.requested_employee_id===row.requested_employee_id||!other.requested_employee_id||!row.requested_employee_id)}).length}
function employees(row){var active=(window.remoteProfiles||[]).filter(function(profile){return profile.active});if(row.requested_employee_id)active=active.filter(function(profile){return String(profile.id)===String(row.requested_employee_id)});return active.map(function(profile){return '<option value="'+esc(profile.id)+'">'+esc(profile.full_name)+'</option>'}).join('')}
function render(filter){var holder=document.getElementById('bookingRequestList');if(!holder)return;var list=rows.filter(function(row){return row.status===filter});holder.innerHTML=list.map(function(row){var clash=conflictCount(row),service=row.services&&row.services.name||'Hizmet',preferred=row.requested_profile&&row.requested_profile.full_name||'Fark etmez',assigned=row.assigned_profile&&row.assigned_profile.full_name||preferred,resolved=row.status!=='pending';return '<article class="booking-request-card '+(resolved?'resolved':'')+'"><h3>'+esc(row.customer_name)+'</h3><p><b>'+esc(row.customer_phone)+'</b></p><p>'+esc(service)+' · '+esc(resolved?assigned:preferred)+'</p><p>'+esc(fmt(row.requested_start_at))+'</p>'+(row.note?'<p>Not: '+esc(row.note)+'</p>':'')+'<p>Talep: '+esc(fmt(row.created_at))+'</p>'+(clash?'<p class="pending-conflict">⚠ Aynı saat için '+clash+' başka bekleyen talep var</p>':'')+(row.status==='rejected'&&row.rejection_reason?'<p>Red nedeni: '+esc(row.rejection_reason)+'</p>':'')+(row.status==='pending'?'<select id="bookingEmployee_'+esc(row.id)+'" aria-label="Onaylanacak çalışan">'+employees(row)+'</select><div class="request-actions"><button onclick="SalonBookingRequests.approve(\''+esc(row.id)+'\')">Onayla</button><button class="reject" onclick="SalonBookingRequests.reject(\''+esc(row.id)+'\')">Reddet</button></div>':'<div class="request-actions"><button class="whatsapp" onclick="SalonBookingRequests.whatsapp(\''+esc(row.id)+'\')">WhatsApp’tan bildir</button></div>')+'</article>'}).join('')||'<div class="empty">Bu durumda talep yok.</div>'}
async function load(){if(!manager())return;ensure();try{var data=await call('admin-list');rows=data.requests||[];var pending=rows.filter(function(row){return row.status==='pending'}).length;document.getElementById('bookingRequestCount').textContent=pending;var badge=document.getElementById('drawerBookingRequestBadge');if(badge)badge.textContent=pending?'('+pending+')':'';render(currentFilter())}catch(error){var holder=document.getElementById('bookingRequestList');if(holder)holder.innerHTML='<div class="empty">'+esc(error.message)+'</div>'}}
async function approve(id){if(busy.has(id))return;var select=document.getElementById('bookingEmployee_'+id),employeeId=select&&select.value;if(!employeeId)return toast('Çalışan seçin','Talebin atanacağı çalışanı seçin.');busy.add(id);try{await call('approve',{method:'POST',body:JSON.stringify({requestId:id,employeeId:employeeId})});toast('Randevu oluşturuldu','Talep onaylandı ve takvime işlendi.');await load();if(typeof window.reloadRemoteData==='function')await window.reloadRemoteData()}catch(error){toast('Talep onaylanamadı',error.message)}finally{busy.delete(id)}}
async function reject(id){if(busy.has(id))return;var reason=window.prompt('Red nedeni (isteğe bağlı):','Saat doldu');if(reason===null)return;busy.add(id);try{await call('reject',{method:'POST',body:JSON.stringify({requestId:id,reason:reason})});toast('Talep reddedildi','Kayıt silinmedi; reddedildi olarak saklandı.');await load()}catch(error){toast('Talep reddedilemedi',error.message)}finally{busy.delete(id)}}
function whatsapp(id){var row=rows.find(function(item){return item.id===id});if(!row)return;var approved=row.status==='approved',service=row.services&&row.services.name||'Hizmet',employee=row.assigned_profile&&row.assigned_profile.full_name||row.requested_profile&&row.requested_profile.full_name||'Salon Modern ekibi',date=fmt(row.requested_start_at),text=approved?'Merhaba '+row.customer_name+',\n\nSalon Modern randevu talebiniz onaylandı. ✓\n\n📅 '+date+'\n✂️ '+service+'\n👤 '+employee+'\n\nRandevunuz kesinleşmiştir.\n\nSalon Modern':'Merhaba '+row.customer_name+',\nseçtiğiniz randevu saati için talebinizi maalesef onaylayamadık.\nYeni bir saat seçmek için:\nhttps://salonmodern.com.tr/randevu';window.location.href='https://wa.me/'+String(row.customer_phone||'').replace(/\D/g,'')+'?text='+encodeURIComponent(text)}
function realtime(){if(!manager()||!window.salonDb||channel)return;channel=window.salonDb.channel('salon-booking-requests-admin').on('postgres_changes',{event:'*',schema:'public',table:'online_booking_requests'},function(){load()}).subscribe()}
var priorEnter=window.enterApp;window.enterApp=function(){var result=priorEnter.apply(this,arguments);if(manager()){ensure();load();realtime()}return result};
var priorShow=window.showPage;window.showPage=function(id){if(id==='bookingRequests'&&!manager())id='home';var result=priorShow.apply(this,arguments);if(id==='bookingRequests')load();return result};
window.SalonBookingRequests={load:load,approve:approve,reject:reject,whatsapp:whatsapp};
installPublicLink();
if(window.currentUser&&manager()){ensure();load();realtime()}
})();
