(function(){
'use strict';
var ready=false;
function manager(){return typeof currentUser!=='undefined'&&currentUser&&currentUser.role==='yonetici'}
function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function toast(a,b){if(typeof window.showAppToast==='function')window.showAppToast(a,b)}
async function ensure(){if(ready||!manager()||!window.salonDb)return;ready=true;var drawer=document.querySelector('#drawerLayer .drawer');if(!drawer)return;var btn=document.createElement('button');btn.className='menu-item manager-menu';btn.innerHTML='⚙ &nbsp; Randevu Ayarları';btn.onclick=open;var admin=document.querySelector("[onclick=\"drawerPage('admin')\"]");drawer.insertBefore(btn,admin||null)}
async function open(){if(!manager())return;var old=document.getElementById('bookingSettingsModal');if(old)old.remove();var modal=document.createElement('div');modal.id='bookingSettingsModal';modal.className='modal show';modal.innerHTML='<div class="sheet" style="max-height:90vh;overflow:auto"><h2>Randevu Ayarları</h2><div id="bookingSettingsBody">Yükleniyor…</div><button class="fab" id="bookingSettingsClose">Kapat</button></div>';document.body.appendChild(modal);document.getElementById('bookingSettingsClose').onclick=function(){modal.remove()};await load()}
async function load(){var body=document.getElementById('bookingSettingsBody');if(!body)return;var s=await window.salonDb.from('booking_settings').select('*').eq('id',true).single(),o=await window.salonDb.from('booking_schedule_overrides').select('*').gte('schedule_date',new Date().toISOString().slice(0,10)).order('schedule_date');if(s.error){body.textContent=s.error.message;return}var x=s.data;body.innerHTML='<label class="field">Online Randevu<select id="bsEnabled"><option value="true"'+(x.online_booking_enabled?' selected':'')+'>Açık</option><option value="false"'+(!x.online_booking_enabled?' selected':'')+'>Kapalı</option></select></label><div class="row"><label class="field">Normal Açılış<input id="bsOpen" type="time" value="'+esc(String(x.default_open_time).slice(0,5))+'"></label><label class="field">Normal Bitiş<input id="bsClose" type="time" value="'+esc(String(x.default_close_time).slice(0,5))+'"></label></div><button class="save" id="bsSave">Kaydet</button><hr style="border:0;border-top:1px solid var(--line);margin:22px 0"><h3>Özel Tarih / Bayram Saati</h3><label class="field">Tarih<input id="boDate" type="date"></label><div class="row"><label class="field">Açılış<input id="boOpen" type="time" value="09:00"></label><label class="field">Bitiş<input id="boClose" type="time" value="22:00"></label></div><label class="field"><input id="boClosed" type="checkbox" style="width:auto"> Bu gün tamamen kapalı</label><button class="save" id="boSave">Özel günü kaydet</button><div id="boList" style="margin-top:15px"></div>';document.getElementById('bsSave').onclick=saveSettings;document.getElementById('boSave').onclick=saveOverride;renderOverrides(o.data||[])}
function renderOverrides(rows){var el=document.getElementById('boList');if(!el)return;el.innerHTML=rows.map(function(r){return '<div class="staff"><div class="item-main"><strong>'+esc(r.schedule_date)+'</strong><small>'+(r.is_closed?'Kapalı':esc(String(r.open_time).slice(0,5))+' – '+esc(String(r.close_time).slice(0,5)))+'</small></div><button class="remove" data-date="'+esc(r.schedule_date)+'">×</button></div>'}).join('')||'<div class="empty">Özel tarih yok.</div>';el.onclick=async function(e){var b=e.target.closest('[data-date]');if(!b)return;await window.salonDb.from('booking_schedule_overrides').delete().eq('schedule_date',b.dataset.date);toast('Özel saat kaldırıldı','Bu tarih normal çalışma saatine döndü.');load()}}
async function saveSettings(){var open=document.getElementById('bsOpen').value,close=document.getElementById('bsClose').value;if(!open||!close||close<=open)return toast('Saatleri kontrol edin','Bitiş saati açılıştan sonra olmalı.');var u=await window.salonDb.auth.getUser(),id=u.data&&u.data.user&&u.data.user.id,r=await window.salonDb.from('booking_settings').update({online_booking_enabled:document.getElementById('bsEnabled').value==='true',default_open_time:open,default_close_time:close,updated_at:new Date().toISOString(),updated_by:id}).eq('id',true);if(r.error)return toast('Kaydedilemedi',r.error.message);toast('Randevu ayarları kaydedildi',open+' – '+close);load()}
async function saveOverride(){var date=document.getElementById('boDate').value,closed=document.getElementById('boClosed').checked,open=document.getElementById('boOpen').value,close=document.getElementById('boClose').value;if(!date)return toast('Tarih seçin','Özel çalışma günü için tarih gerekli.');if(!closed&&(!open||!close||close<=open))return toast('Saatleri kontrol edin','Bitiş saati açılıştan sonra olmalı.');var u=await window.salonDb.auth.getUser(),id=u.data&&u.data.user&&u.data.user.id,r=await window.salonDb.from('booking_schedule_overrides').upsert({schedule_date:date,open_time:closed?null:open,close_time:closed?null:close,is_closed:closed,updated_at:new Date().toISOString(),updated_by:id},{onConflict:'schedule_date'});if(r.error)return toast('Kaydedilemedi',r.error.message);toast('Özel çalışma saati kaydedildi',date);load()}
var prior=window.enterApp;window.enterApp=function(){var r=prior.apply(this,arguments);setTimeout(ensure,0);return r};if(manager())setTimeout(ensure,0);
window.SalonBookingSettings={open:open};
})();
