(function(){
'use strict';
var VERSION='2.2.0',session={last:null,pending:null,ambiguity:null,focusedClientId:null,focusedEmployeeId:null,focusedDate:null,focusedSlot:null},cache=new Map(),CACHE_MS=45000,CONTEXT_MS=30*60*1000;
var STATUS_LABEL={approaching:'Yaklaşıyor',due:'Zamanı Geldi',overdue:'Gecikti',risk:'Kaybedilme Riski',regular:'Düzenli',insufficient:'Yeterli veri yok'};
var DAY_NAMES=['pazar','pazartesi','sali','carsamba','persembe','cuma','cumartesi'];
function fold(value){return String(value||'').toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[’']/g,'').replace(/([a-z])\1{2,}/g,'$1$1').replace(/[^a-z0-9:\s.-]/g,' ').replace(/\s+/g,' ').trim()}
function compact(value){return fold(value).replace(/\s/g,'')}
var NORMALIZATION_RULES=[
  [/\benson\b/g,'en son'],[/\bkacgundur\b/g,'kac gundur'],[/\brandevularm\b/g,'randevularim'],
  [/\bdortbucuk\b/g,'dort bucuk'],[/\bikibucuk\b/g,'iki bucuk'],[/\bbosssaat/g,'bos saat'],
  [/\bbugunki\b/g,'bugunku'],[/\byarinki\b/g,'yarinki'],[/\bgelmiyen\b/g,'gelmeyen'],
  [/\bmusterler\b/g,'musteriler'],[/\brandevlar\b/g,'randevular']
];
function normalizeCommand(value){var n=fold(value);NORMALIZATION_RULES.forEach(function(rule){n=n.replace(rule[0],rule[1])});return n.replace(/\s+/g,' ').trim()}
function normalizeLoginName(value){return fold(String(value||'').trim().split('@')[0]).replace(/\s+/g,'')}
function esc(value){return typeof safe==='function'?safe(value):String(value??'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function attr(value){return typeof jsAttr==='function'?jsAttr(String(value)):JSON.stringify(String(value))}
function isManager(){return currentUser&&currentUser.role==='yonetici'}
function isoAdd(date,days){var d=new Date(date+'T12:00:00');d.setDate(d.getDate()+days);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function dateRange(date){return {start:date+'T00:00:00+03:00',end:isoAdd(date,1)+'T00:00:00+03:00'}}
function parseDate(text){var n=fold(text),today=localDate(0);if(/\bobur gun\b/.test(n))return isoAdd(today,2);if(/\byarin\b/.test(n))return isoAdd(today,1);if(/\bbugun\b/.test(n))return today;
  var explicit=n.match(/\b(\d{1,2})[ .\/-](\d{1,2})(?:[ .\/-](\d{4}))?\b/);if(explicit)return (explicit[3]||today.slice(0,4))+'-'+String(explicit[2]).padStart(2,'0')+'-'+String(explicit[1]).padStart(2,'0');
  var monthDay=n.match(/\bayin\s+(\d{1,2})/);if(monthDay){var proposed=today.slice(0,8)+String(Number(monthDay[1])).padStart(2,'0');if(proposed<today){var next=new Date(today+'T12:00:00');next.setMonth(next.getMonth()+1,Number(monthDay[1]));return next.getFullYear()+'-'+String(next.getMonth()+1).padStart(2,'0')+'-'+String(next.getDate()).padStart(2,'0')}return proposed}
  var months={ocak:1,subat:2,mart:3,nisan:4,mayis:5,haziran:6,temmuz:7,agustos:8,eylul:9,ekim:10,kasim:11,aralik:12},monthMatch=n.match(/\b(\d{1,2})\s+(ocak|subat|mart|nisan|mayis|haziran|temmuz|agustos|eylul|ekim|kasim|aralik)(?:\s+(\d{4}))?/);if(monthMatch)return (monthMatch[3]||today.slice(0,4))+'-'+String(months[monthMatch[2]]).padStart(2,'0')+'-'+String(monthMatch[1]).padStart(2,'0');
  for(var i=0;i<DAY_NAMES.length;i++)if(new RegExp('\\b'+DAY_NAMES[i]+'(?: gunu| gunki|ki)?\\b').test(n)){var now=new Date(today+'T12:00:00'),delta=(i-now.getDay()+7)%7;if(/gelecek/.test(n))delta+=7;return isoAdd(today,delta)}return null}
var TURKISH_NUMBERS={bir:1,iki:2,uc:3,dort:4,bes:5,alti:6,yedi:7,sekiz:8,dokuz:9,on:10,onbir:11,oniki:12,onuc:13,ondort:14,onbes:15,onalti:16,onyedi:17,onsekiz:18,ondokuz:19,yirmi:20,yirmibir:21,yirmiiki:22,yirmiuc:23};
function turkishNumber(value){var compacted=fold(value).replace(/\s+/g,'').replace(/(?:te|ta|de|da|ye|ya|e|a)$/,'');if(TURKISH_NUMBERS[compacted]!=null)return TURKISH_NUMBERS[compacted];var spaced=fold(value).trim().split(/\s+/),total=0;for(var i=0;i<spaced.length;i++){var part=spaced[i].replace(/(?:te|ta|de|da|ye|ya|e|a)$/,'');if(TURKISH_NUMBERS[part]==null)return null;total+=TURKISH_NUMBERS[part]}return total||null}
function normalizeSalonHour(hour,context){if(hour==null)return null;var h=Number(hour),n=fold(context);if(h<8&&!/\bsabah\b/.test(n))h+=12;return h>=8&&h<=23?h:null}
function parseTime(text){var n=fold(text),m=n.match(/(?:saat\s*)?(\d{1,2})[:.]([0-5]\d)/);if(m){var exact=Number(m[1]);return exact>=8&&exact<=23?String(exact).padStart(2,'0')+':'+m[2]:null}
  var numeric=n.match(/\b(?:saat|ogleden sonra|oglen|aksamustu)\s+(\d{1,2})(?:\s+(bucu(?:k|g)\w*|otuz))?/);if(numeric){var numericHour=normalizeSalonHour(Number(numeric[1]),n);return numericHour==null?null:String(numericHour).padStart(2,'0')+':'+(numeric[2]?'30':'00')}
  var words='(?:yirmi\\s+(?:bir|iki|uc)|on\\s+(?:bir|iki|uc|dort|bes|alti|yedi|sekiz|dokuz)|yirmi|on|bir|iki|uc|dort|bes|alti|yedi|sekiz|dokuz)';
  var spoken=n.match(new RegExp('\\b(?:saat|ogleden sonra|oglen|aksamustu)\\s+('+words+')(?:te|ta|de|da|ye|ya|e|a)?(?:\\s+(bucu(?:k|g)\\w*|otuz))?'))||n.match(new RegExp('\\b('+words+')(?:te|ta|de|da|ye|ya|e|a)?\\s+(bucu(?:k|g)\\w*|otuz)'));
  if(!spoken)return null;var hour=normalizeSalonHour(turkishNumber(spoken[1]),n);return hour==null?null:String(hour).padStart(2,'0')+':'+(spoken[2]?'30':'00')}
function parseLimit(text,fallback){var m=fold(text).match(/(?:son|ilk|en cok gelen)\s+(\d{1,2})\b/);return Math.min(50,Math.max(1,m?Number(m[1]):fallback||10))}
function parseDays(text){var m=fold(text).match(/(\d{1,3})\s+gundur/);return m?Number(m[1]):null}
function parseTimeRange(text){var n=normalizeCommand(String(text||'').replace(/[–—]/g,'-')),m=n.match(/\b(\d{1,2})[:.]([0-5]\d)\s*(?:-|ile|ve)\s*(\d{1,2})[:.]([0-5]\d)\b/);if(!m)return null;var start=Number(m[1])*60+Number(m[2]),end=Number(m[3])*60+Number(m[4]);return start>=480&&end<=1440&&end>start?{start:String(m[1]).padStart(2,'0')+':'+m[2],end:String(m[3]).padStart(2,'0')+':'+m[4]}:null}
function weekRange(text){var today=localDate(0),d=new Date(today+'T12:00:00'),mondayOffset=(d.getDay()+6)%7,start=isoAdd(today,-mondayOffset);if(/gelecek hafta/.test(normalizeCommand(text)))start=isoAdd(start,7);return {start:start,end:isoAdd(start,7)}}
function cleanClientTerm(value){return String(value||'').replace(/[’']?(?:nin|nın|nun|nün|in|ın|un|ün)$/i,'').replace(/\b(musteri(?:si|nin)?|randevu(?:su|sunu|larini)?|son|en|kac|ortalama|genelde)\b/gi,' ').replace(/\s+/g,' ').trim()}
function clientPrefix(command,marker){var index=fold(command).indexOf(marker);return index<1?'':cleanClientTerm(String(command).slice(0,index))}
function editDistance(a,b){var previous=Array.from({length:b.length+1},function(_,i){return i});for(var i=1;i<=a.length;i++){var current=[i];for(var j=1;j<=b.length;j++)current[j]=Math.min(current[j-1]+1,previous[j]+1,previous[j-1]+(a[i-1]===b[j-1]?0:1));previous=current}return previous[b.length]}
function employeeFrom(text){var n=fold(text),active=(remoteProfiles||[]).filter(function(p){return p.active}),matches=active.filter(function(p){return n.includes(fold(p.full_name).split(' ')[0])});if(matches.length===1)return matches[0];if(matches.length>1)return null;var tokens=n.split(' '),ranked=active.map(function(p){var first=fold(p.full_name).split(' ')[0],score=Math.min.apply(null,tokens.map(function(t){return editDistance(t,first)}));return {profile:p,score:score}}).sort(function(a,b){return a.score-b.score});return ranked.length&&ranked[0].score<=1&&(!ranked[1]||ranked[1].score>ranked[0].score)?ranked[0].profile:null}
var COMMAND_EXAMPLES=[
  ['client_last_visit','Ahmet en son ne zaman geldi?'],['client_history','Ahmet’in son 5 ziyaretini göster.'],['client_absence_days','Ahmet kaç gündür gelmiyor?'],
  ['inactive_customers','30 gündür gelmeyenleri göster.'],['risk_customers','Kaybedilme riski olanları göster.'],['appointments','Bugünkü randevuları göster.'],
  ['free_slots','Yarın boş saatler ne?'],['first_free_slot','Yarın ilk boş saat ne?'],['weekly_appointment_count','Bu hafta kaç randevu var?'],
  ['weekly_free_slots','Bu haftanın boşluklarını göster.'],['cancelled_appointments','Bugün iptal edilen randevuları göster.'],['salon_summary','Bugünkü salon özetini göster.']
];
function commandSuggestions(text){var n=normalizeCommand(text),tokens=n.split(' ');return COMMAND_EXAMPLES.map(function(row){var sample=normalizeCommand(row[1]),common=tokens.filter(function(t){return t.length>2&&sample.includes(t)}).length,score=editDistance(n,sample)-common*3;return {intent:row[0],example:row[1],score:score}}).sort(function(a,b){return a.score-b.score}).slice(0,3)}
function extractEntities(command){var normalized=normalizeCommand(command),range=parseTimeRange(command);return {raw:command,normalized:normalized,date:parseDate(normalized),time:parseTime(normalized),range:range,days:parseDays(normalized),limit:parseLimit(normalized,10),employee:employeeFrom(normalized),period:/gelecek hafta/.test(normalized)?'next_week':/bu hafta/.test(normalized)?'this_week':/bu ay/.test(normalized)?'this_month':null}}
function confidenceFor(intent,entities){if(!intent)return 0;if(['create_appointment','move_appointment','transfer_appointment','cancel_appointment'].includes(intent))return entities.date||entities.time||(entities.employee&&entities.employee.id)?0.92:0.72;return entities.normalized.length>5?0.95:0.75}
function parser(command){var entities=extractEntities(command),n=entities.normalized,c=compact(command),date=entities.date,time=entities.time,days=entities.days,limit=entities.limit,employee=entities.employee,intent=null,client='',compareTerms=null;
  if(/^(yardim|ne sorabilirim|ne yapabilirsin)/.test(n))intent='help';
  else if(/salon (ozet|nasil)|bugunku salon|bugun nelere dikkat/.test(n))intent='salon_summary';
  else if(/en yogun gun/.test(n))intent='busiest_day';
  else if(/kac musterimiz var/.test(n))intent='customer_count';
  else if(/calisan performans/.test(n))intent='employee_performance';
  else if(/en cok calisan|en cok musteriye kim bakti|hangi calisan.*yogun/.test(n))intent='employee_workload';
  else if(/para kazandirabilecek|boslu(?:gu|klari) doldurabilecek|bos saatlere uygun/.test(n))intent='gap_candidates';
  else if(/riskli.*bugun gelebilecek/.test(n))intent='risk_candidates';
  else if(/bu ay en cok gelen/.test(n)){intent='frequent_customers';limit=parseLimit(command,10)}
  else if(/eskiden duzenli|gelmeyi birakan|son zamanlarda gelmeyi/.test(n))intent='lapsed_customers';
  else if(/en duzenli/.test(n))intent='regular_customers';
  else if(/gelme zamani gelen/.test(n))intent='due_customers';
  else if(/geciken/.test(n))intent='overdue_customers';
  else if(/kaybedilme riski|^(?:bugun\s+)?riskli musteriler|riskli musterileri/.test(n))intent='risk_customers';
  else if(days!==null&&/gelmeyen/.test(n))intent='inactive_customers';
  else if(/bugun ilgilenmem/.test(n))intent='attention_customers';
  else if(/bu hafta gelmesi gereken/.test(n))intent='due_this_week';
  else if(/(.+?)\s+ile\s+(.+?)(?:nin)?\s+son ziyaretlerini karsilastir/.test(n)){intent='compare_clients';var comparison=n.match(/(.+?)\s+ile\s+(.+?)(?:nin)?\s+son ziyaretlerini karsilastir/);compareTerms=[cleanClientTerm(comparison[1]),cleanClientTerm(comparison[2])]}
  else if(/iptal edilen randevu/.test(n))intent='cancelled_appointments';
  else if(/bu hafta kac randevu|bu haftaki randevu sayisi/.test(n))intent='weekly_appointment_count';
  else if(/bu haftanin bosluk|bu hafta bos saat/.test(n))intent='weekly_free_slots';
  else if(/ilk bos saat|en yakin bosluk/.test(n))intent='first_free_slot';
  else if(/kim bos/.test(n)||/saat\s*\d{1,2}[:.]\d{2}.*kim bos/.test(n))intent='who_free';
  else if(employee&&/bos mu|bos saat/.test(n))intent='employee_free_slots';
  else if(/bos saat/.test(n)||/bosluk/.test(n))intent='free_slots';
  else if(/kac randevu/.test(n))intent='appointment_count';
  else if(/^(.+?)\s+randevularini(?:\s+goster)?/.test(n)){intent='client_appointments';client=cleanClientTerm(n.match(/^(.+?)\s+randevularini/)[1])}
  else if(/randevu.*(goster|ne)|randevular|benim programim/.test(n)&&!/(olustur|ekle|al|gecir|tasi|iptal)/.test(n))intent=employee?'employee_appointments':'appointments';
  else if(/randevu.*(olustur|ekle|ver)/.test(n)){intent='create_appointment';var createMatch=String(command).match(/^(.+?)(?:[’']?(?:ya|ye|a|e))?\s+(?=(?:bugün|yarın|öbür gün|pazartesi|salı|çarşamba|perşembe|cuma|cumartesi|pazar|ayın\s+\d{1,2}|\d{1,2}(?:[ .\/-]|\s+(?:ocak|şubat|mart|nisan|mayıs|haziran|temmuz|ağustos|eylül|ekim|kasım|aralık))))/i);client=cleanClientTerm(createMatch?createMatch[1]:String(command).split(/\brandevu/i)[0])}
  else if(/randevu.*iptal/.test(n)){intent='cancel_appointment';client=clientPrefix(command,' randevu')}
  else if(/randevu.*(?:gecir|aktar)/.test(n)){intent='transfer_appointment';client=clientPrefix(command,' randevu')}
  else if(employee&&/(?:gecir|aktar)/.test(n)){intent='transfer_appointment';client=cleanClientTerm(String(command).split(/[’']?[ıi]?s+\b(?:Mehmet|Halil|Cengiz|Talip)\b/i)[0])}
  else if(/randevu.*(?:al|tasi|degistir)/.test(n)){intent='move_appointment';client=clientPrefix(command,' randevu')}
  else if(/bu musterinin son\s+(?:uc|3)\s+(?:islemini|hizmetini)/.test(n)){intent='client_recent_services';client='bu müşteri';limit=3}
  else {
    var customerPatterns=[
      ['client_last_visit',/(.+?)\s+(?:en\s*)?son\s+(?:ne zaman geldi|ziyaretini goster|ne zaman tiras ettik)/],
      ['client_absence_days',/(.+?)\s+kac gundur gelmiyor/],['client_visit_count',/(.+?)\s+kac (?:kere|kez) geldi/],
      ['client_history',/(.+?)\s+son\s+\d+\s+ziyaretini/],['client_average',/(.+?)\s+ortalama kac gunde/],
      ['client_due',/(.+?)\s+gelme zamani geldi mi/],['client_risk',/(.+?)\s+riskli musteri mi/],
      ['client_next_visit',/(.+?)\s+(?:bir sonraki )?tahmini gelis/],['client_card',/(.+?)\s+musteri kartini/],
      ['client_recent_services',/(.+?)\s+son\s+(?:uc|3)\s+(?:islemini|hizmetini)/],['client_notes',/(.+?)\s+notlarini/],['client_appointments',/(.+?)\s+randevularini/],
      ['client_top_service',/(.+?)\s+en cok hangi hizmet/],['client_preferred_employee',/(.+?)\s+genelde hangi calisana/]
    ];for(var pi=0;pi<customerPatterns.length&&!intent;pi++){var hit=n.match(customerPatterns[pi][1]);if(hit){intent=customerPatterns[pi][0];client=cleanClientTerm(hit[1])}}
  }
  if(intent==='client_recent_services')limit=3;
  var parsed={intent:intent,raw:command,normalized:n,client:client,employee:employee,date:date,time:time,after:/sonra/.test(n)?time:null,days:days,limit:limit,period:entities.period,range:entities.range,compareTerms:compareTerms};
  if(intent==='client_recent_services'&&/^bu musteri/.test(fold(client))&&session.focusedClientId)parsed.clientId=session.focusedClientId;
  parsed.confidence=confidenceFor(intent,entities);parsed.suggestions=commandSuggestions(n);return parsed;
}
function resultNode(){return document.getElementById('salonAssistantResult')}
function render(html){var node=resultNode();if(node)node.innerHTML=html;var home=document.getElementById('phase2AssistantResult');if(home)home.innerHTML=html}
function notice(message){render('<div class="notice">'+esc(message)+'</div>')}
function loading(){render('<div class="empty">Bilgiler getiriliyor…</div>')}
var INTENT_LABELS={appointments:'Randevular',employee_appointments:'Çalışan randevuları',appointment_count:'Randevu sayısı',free_slots:'Boş saatler',employee_free_slots:'Çalışan boş saatleri',who_free:'Boş çalışanlar',first_free_slot:'İlk boş saat',weekly_appointment_count:'Haftalık randevu sayısı',weekly_free_slots:'Haftalık boşluklar',cancelled_appointments:'İptal edilen randevular',compare_clients:'Müşteri karşılaştırma',client_recent_services:'Son işlemler'};
function understoodHtml(parsed){if(!parsed)return '';var bits=[INTENT_LABELS[parsed.intent]||'Salon Asistanı'];if(parsed.client)bits.push(parsed.client);if(parsed.employee)bits.push(parsed.employee.full_name);if(parsed.date)bits.push(friendlyDate(parsed.date));if(parsed.range)bits.push(parsed.range.start+'–'+parsed.range.end);else if(parsed.time)bits.push(parsed.time);return '<div class="assistant-understood"><strong>Anladığım:</strong> '+bits.map(esc).join(' · ')+'</div>'}
function answer(parsed,content){return '<div class="assistant-answer">'+understoodHtml(parsed)+content+'</div>'}
function suggestionHtml(parsed){var suggestions=(parsed&&parsed.suggestions||[]).slice(0,3);return '<div class="notice"><strong>Bu komutu güvenle anlayamadım.</strong><br>Şunlardan birini deneyebilirsiniz:</div><div class="assistant-help">'+suggestions.map(function(s){return '<button type="button" onclick="assistantUseText('+attr(s.example)+')">'+esc(s.example)+'</button>'}).join('')+'</div>'}
function phaseRows(){return window.SalonPhase2Test&&SalonPhase2Test.rows?SalonPhase2Test.rows():[]}
function clientById(id){return (remoteClients||[]).find(function(c){return String(c.id)===String(id)&&c.active!==false})}
function profileById(id){return (remoteProfiles||[]).find(function(p){return String(p.id)===String(id)})}
function visibleClient(row){if(isManager())return true;return String(row.preferred_employee_id||'')===String(currentUser.id)||(appts||[]).some(function(a){return String(a.clientId)===String(row.client_id)&&String(a.employeeId)===String(currentUser.id)})}
function matchingClients(term){var key=fold(term),active=(remoteClients||[]).filter(function(c){return c.active!==false}),rows=active.filter(function(c){return fold(c.full_name).includes(key)});if(!rows.length&&/[iu]$/.test(key))rows=active.filter(function(c){return fold(c.full_name).includes(key.slice(0,-1))});if(!rows.length&&key.length>=3){var ranked=active.map(function(c){var name=fold(c.full_name),parts=name.split(' '),score=Math.min(editDistance(key,name),Math.min.apply(null,parts.map(function(part){return editDistance(key,part)})));return {client:c,score:score}}).sort(function(a,b){return a.score-b.score}),best=ranked[0]&&ranked[0].score,limit=key.length<=5?1:2;if(best<=limit)rows=ranked.filter(function(item){return item.score===best}).map(function(item){return item.client})}return rows.slice(0,20)}
function maskPhone(phone){var d=String(phone||'').replace(/\D/g,'');return d?('••• ••• '+d.slice(-4)):'Telefon yok'}
function statusFor(row){if(!row||Number(row.distinct_visit_days||row.visit_count||0)<3||!row.average_visit_days)return {key:'insufficient',label:STATUS_LABEL.insufficient};var elapsed=Math.max(0,Math.floor((Date.parse(localDate(0)+'T12:00:00')-Date.parse(row.last_visit_date+'T12:00:00'))/86400000)),ratio=elapsed/Number(row.average_visit_days),key=ratio>=1.75?'risk':ratio>=1.25?'overdue':ratio>=1?'due':ratio>=.75?'approaching':'regular';return {key:key,label:STATUS_LABEL[key],elapsed:elapsed}}
function clientPickCards(matches,parsed){session.ambiguity={parsed:parsed,ids:matches.map(function(c){return c.id})};var rows=phaseRows();return '<div class="assistant-answer"><h3>'+matches.length+' müşteri buldum. Hangisini kastediyorsunuz?</h3>'+matches.map(function(c){var row=rows.find(function(r){return String(r.client_id)===String(c.id)}),employee=profileById(row&&row.preferred_employee_id);return '<button type="button" class="assistant-pick" onclick="selectSalonAssistantClient('+attr(c.id)+')"><strong>'+esc(c.full_name)+'</strong><small>'+esc(maskPhone(c.phone))+' · Son ziyaret: '+esc(row&&row.last_visit_date?friendlyDate(row.last_visit_date):'Yok')+' · '+esc(employee?employee.full_name:'Tercih yok')+'</small></button>'}).join('')+'</div>'}
async function resolveClient(parsed){if(parsed.clientId){var exact=clientById(parsed.clientId);return exact&&visibleClient(phaseRows().find(function(r){return String(r.client_id)===String(exact.id)})||{client_id:exact.id})?exact:null}var matches=matchingClients(parsed.client).filter(function(c){var row=phaseRows().find(function(r){return String(r.client_id)===String(c.id)})||{client_id:c.id};return visibleClient(row)});if(!matches.length)return null;if(matches.length>1){render(clientPickCards(matches,parsed));return 'ambiguous'}return matches[0]}
window.selectSalonAssistantClient=function(id){if(!session.ambiguity||!session.ambiguity.ids.map(String).includes(String(id)))return;var parsed=session.ambiguity.parsed;session.ambiguity=null;session.focusedClientId=id;parsed.clientId=id;execute(parsed)};
function comparisonPickCards(matches,parsed,index){session.ambiguity={kind:'comparison',parsed:parsed,index:index,ids:matches.map(function(c){return c.id})};return '<div class="assistant-answer"><h3>'+esc(parsed.compareTerms[index])+' için '+matches.length+' müşteri buldum. Hangisi?</h3>'+matches.map(function(c){return '<button type="button" class="assistant-pick" onclick="selectSalonAssistantComparisonClient('+attr(c.id)+')"><strong>'+esc(c.full_name)+'</strong><small>'+esc(maskPhone(c.phone))+'</small></button>'}).join('')+'</div>'}
window.selectSalonAssistantComparisonClient=function(id){var state=session.ambiguity;if(!state||state.kind!=='comparison'||!state.ids.map(String).includes(String(id)))return;state.parsed.compareIds=state.parsed.compareIds||[];state.parsed.compareIds[state.index]=id;var parsed=state.parsed;session.ambiguity=null;execute(parsed)};
async function resolveComparison(parsed){parsed.compareIds=parsed.compareIds||[];var resolved=[];for(var i=0;i<2;i++){if(parsed.compareIds[i]){resolved[i]=clientById(parsed.compareIds[i]);continue}var matches=matchingClients(parsed.compareTerms[i]).filter(function(c){var row=phaseRows().find(function(r){return String(r.client_id)===String(c.id)})||{client_id:c.id};return visibleClient(row)});if(!matches.length)return null;if(matches.length>1){render(comparisonPickCards(matches,parsed,i));return 'ambiguous'}resolved[i]=matches[0];parsed.compareIds[i]=matches[0].id}return resolved}
function customerActions(id){return '<div class="assistant-actions"><button onclick="openCustomerDetail('+attr(id)+')">Müşteri Kartı</button><button onclick="assistantOpenHistory('+attr(id)+')">Geçmiş</button><button onclick="newAppointmentForCustomer('+attr(id)+')">Randevu Ver</button><button onclick="openSmartCustomerWhatsApp('+attr(id)+')">WhatsApp</button></div>'}
function customerCard(row){var client=clientById(row.client_id)||row,status=statusFor(row),employee=profileById(row.preferred_employee_id);return '<article class="assistant-result-card"><strong>'+esc(client.full_name||row.full_name)+'</strong><small>Son geliş: '+esc(row.last_visit_date?friendlyDate(row.last_visit_date):'Kayıt yok')+' · '+(status.elapsed==null?'Yeterli veri yok':status.elapsed+' gün önce')+'<br>Ortalama geliş: '+(row.average_visit_days?row.average_visit_days+' gün':'Yeterli veri yok')+' · '+esc(status.label)+(employee?'<br>Tercih: '+esc(employee.full_name):'')+'</small>'+customerActions(row.client_id)+'</article>'}
function remember(type,items,parsed){session.last={type:type,items:items,parsed:parsed,at:Date.now()};if(parsed){if(parsed.date)session.focusedDate=parsed.date;if(parsed.employee)session.focusedEmployeeId=parsed.employee.id}if(type==='slots'&&items[0])session.focusedSlot=items[0]}
function cards(rows,parsed){remember('clients',rows,parsed);return rows.map(customerCard).join('')||'<div class="empty">Kayıt bulunamadı.</div>'}
async function clientHistory(id,limit){var key='history:'+id+':'+limit,hit=cache.get(key);if(hit&&Date.now()-hit.at<CACHE_MS)return hit.data;var q=await salonDb.from('appointments').select('id,client_id,client_name,service_name,employee_id,scheduled_at,amount,status').eq('client_id',id).order('scheduled_at',{ascending:false}).limit(limit);if(q.error)throw q.error;cache.set(key,{at:Date.now(),data:q.data||[]});return q.data||[]}
function historyHtml(rows){return rows.map(function(a){var slot=toIstanbul(a.scheduled_at),employee=profileById(a.employee_id);return '<div class="assistant-row"><strong>'+esc(a.service_name||'İşlem')+'</strong><small>'+esc(friendlyDate(slot.date))+' · '+esc(slot.time)+' · '+esc(employee?employee.full_name:'Çalışan')+'</small></div>'}).join('')||'<div class="empty">Kayıt bulunamadı.</div>'}
window.assistantOpenHistory=async function(id){session.focusedClientId=id;loading();try{var rows=await clientHistory(id,5);remember('appointments',rows,{intent:'client_history',clientId:id});render('<div class="assistant-answer"><h3>Son ziyaretler</h3>'+historyHtml(rows)+'</div>')}catch(e){notice(e.message||'Geçmiş yüklenemedi.')}};
async function dayAppointments(date){var key='day:'+date,hit=cache.get(key);if(hit&&Date.now()-hit.at<CACHE_MS)return hit.data;var range=dateRange(date),q=await salonDb.from('appointments').select('id,client_id,client_name,service_id,service_name,amount,employee_id,scheduled_at,duration_minutes,status,created_by').gte('scheduled_at',range.start).lt('scheduled_at',range.end).neq('status','cancelled').order('scheduled_at');if(q.error)throw q.error;var rows=(q.data||[]).map(remoteAppointment);cache.set(key,{at:Date.now(),data:rows});return rows}
async function rangeAppointments(start,end,options){options=options||{};var employeeId=!isManager()?currentUser.id:options.employeeId,key='range:'+start+':'+end+':'+(options.cancelled?'cancelled':'active')+':'+(employeeId||'all'),hit=cache.get(key);if(hit&&Date.now()-hit.at<CACHE_MS)return hit.data;var q=salonDb.from('appointments').select('id,client_id,client_name,service_id,service_name,amount,employee_id,scheduled_at,duration_minutes,status,created_by').gte('scheduled_at',start+'T00:00:00+03:00').lt('scheduled_at',end+'T00:00:00+03:00');q=options.cancelled?q.eq('status','cancelled'):q.neq('status','cancelled');if(employeeId)q=q.eq('employee_id',employeeId);q=await q.order('scheduled_at');if(q.error)throw q.error;var rows=(q.data||[]).map(remoteAppointment);cache.set(key,{at:Date.now(),data:rows});return rows}
function appointmentCards(rows,parsed){remember('appointments',rows,parsed);return rows.map(function(a){return '<article class="assistant-result-card"><strong>'+esc(a.customer)+'</strong><small>'+esc(friendlyDate(appointmentDate(a)))+' · '+esc(a.time)+' · '+esc(a.staff)+' · '+esc(a.operation)+'</small></article>'}).join('')||'<div class="empty">Kayıt bulunamadı.</div>'}
function slotGroups(date,rows,profiles,after){var min=after?Number(after.slice(0,2))*60+Number(after.slice(3)):480,out=[];profiles.forEach(function(p){var starts=[];for(var m=Math.max(480,min);m<1440;m+=30){var time=String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0'),busy=rows.some(function(a){if(String(a.employeeId)!==String(p.id))return false;var s=Number(a.time.slice(0,2))*60+Number(a.time.slice(3)),e=s+Number(a.duration||30);return m<e&&m+30>s}),closed=closedSlotFor(date,time,30,p.id);if(!busy&&!closed)starts.push(m)}var groups=[];starts.forEach(function(s){var last=groups[groups.length-1];if(last&&last.end===s)last.end=s+30;else groups.push({start:s,end:s+30})});groups.forEach(function(g){out.push({employeeId:p.id,employeeName:p.full_name,start:g.start,end:g.end,date:date})})});return out}
function clock(m){return m>=1440?'24:00':String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function slotsHtml(slots,parsed){remember('slots',slots,parsed);return slots.map(function(s){return '<div class="assistant-row"><strong>'+esc(s.employeeName)+'</strong><small>'+esc(friendlyDate(s.date))+' · '+clock(s.start)+'–'+clock(s.end)+'</small></div>'}).join('')||'<div class="empty">Uygun boş saat bulunamadı.</div>'}
function visibleProfiles(parsed){if(!isManager())return (remoteProfiles||[]).filter(function(p){return p.active&&String(p.id)===String(currentUser.id)});if(parsed.employee)return [parsed.employee];return (remoteProfiles||[]).filter(function(p){return p.active})}
function helpHtml(){return '<div class="assistant-help"><h3>Şunları sorabilirsiniz</h3><strong>Müşteriler</strong><button onclick="assistantUseText(\'Ahmet en son ne zaman geldi?\')">Ahmet en son ne zaman geldi?</button><strong>Randevular</strong><button onclick="assistantUseText(\'Bugünkü randevuları göster.\')">Bugünkü randevuları göster.</button><strong>Takvim</strong><button onclick="assistantUseText(\'Yarın boş saatler ne?\')">Yarın boş saatler ne?</button><strong>Analiz</strong><button onclick="assistantUseText(\'30 gündür gelmeyenleri göster.\')">30 gündür gelmeyenleri göster.</button><strong>Salon</strong><button onclick="assistantUseText(\'Bugünkü salon özetini göster.\')">Bugünkü salon özetini göster.</button></div>'}
window.assistantUseText=function(text){var input=document.getElementById('salonAssistantInput');if(input){input.value=text;window.runSalonAssistant({preventDefault:function(){}})}};
function analysisRows(intent,parsed){var rows=phaseRows().filter(visibleClient),today=localDate(0),week=isoAdd(today,7);rows=rows.map(function(r){r._status=statusFor(r);return r});if(intent==='inactive_customers')rows=rows.filter(function(r){return r._status.elapsed!=null&&r._status.elapsed>=parsed.days});else if(intent==='due_customers')rows=rows.filter(function(r){return r._status.key==='due'});else if(intent==='overdue_customers')rows=rows.filter(function(r){return r._status.key==='overdue'});else if(intent==='risk_customers'||intent==='risk_candidates')rows=rows.filter(function(r){return r._status.key==='risk'});else if(intent==='attention_customers')rows=rows.filter(function(r){return ['due','overdue','risk'].includes(r._status.key)});else if(intent==='due_this_week')rows=rows.filter(function(r){return r.expected_next_visit_date>=today&&r.expected_next_visit_date<=week});else if(intent==='regular_customers')rows=rows.filter(function(r){return r._status.key==='regular'&&r.average_visit_days}).sort(function(a,b){return a.average_visit_days-b.average_visit_days});else if(intent==='lapsed_customers')rows=rows.filter(function(r){return ['overdue','risk'].includes(r._status.key)&&Number(r.distinct_visit_days||0)>=3});return rows.slice(0,parsed.limit||50)}
async function frequentCustomers(parsed){var today=localDate(0),start=today.slice(0,7)+'-01',end=isoAdd(today,1),q=await salonDb.from('appointments').select('client_id,scheduled_at,status').not('client_id','is',null).gte('scheduled_at',start+'T00:00:00+03:00').lt('scheduled_at',end+'T00:00:00+03:00').neq('status','cancelled');if(q.error)throw q.error;var counts={};(q.data||[]).forEach(function(a){counts[a.client_id]=(counts[a.client_id]||0)+1});var rows=phaseRows().filter(visibleClient).filter(function(r){return counts[r.client_id]}).sort(function(a,b){return counts[b.client_id]-counts[a.client_id]}).slice(0,parsed.limit);rows.forEach(function(r){r._monthCount=counts[r.client_id]});remember('clients',rows,parsed);return rows.map(function(r){return customerCard(r).replace('</small>','<br>Bu ay: '+r._monthCount+' ziyaret</small>')}).join('')||'<div class="empty">Bu ay ziyaret kaydı yok.</div>'}
async function executeClient(parsed){var client=await resolveClient(parsed);if(client==='ambiguous')return;if(!client){notice('Kayıt bulunamadı. Müşteri adını biraz daha açık yazın.');return}session.focusedClientId=client.id;var row=phaseRows().find(function(r){return String(r.client_id)===String(client.id)})||{client_id:client.id,full_name:client.full_name,phone:client.phone,visit_count:0,distinct_visit_days:0},status=statusFor(row),history;
  if(parsed.intent==='client_card'){openCustomerDetail(client.id);return}
  if(parsed.intent==='client_history'||parsed.intent==='client_appointments'||parsed.intent==='client_recent_services'){history=await clientHistory(client.id,parsed.intent==='client_appointments'?20:parsed.limit);remember('appointments',history,parsed);render(answer(parsed,'<h3>'+esc(client.full_name)+'</h3>'+historyHtml(history)+customerActions(client.id)));return}
  var value='';if(parsed.intent==='client_last_visit')value=row.last_visit_date?'Son geliş: '+friendlyDate(row.last_visit_date):'Kayıt bulunamadı.';else if(parsed.intent==='client_absence_days')value=status.elapsed==null?'Bunu hesaplamak için yeterli ziyaret geçmişi yok.':status.elapsed+' gündür gelmiyor.';else if(parsed.intent==='client_visit_count')value=Number(row.visit_count||0)+' kez geldi.';else if(parsed.intent==='client_average')value=row.average_visit_days?'Ortalama '+row.average_visit_days+' günde bir geliyor.':'Bunu hesaplamak için yeterli ziyaret geçmişi yok.';else if(parsed.intent==='client_due')value=status.key==='due'?'Evet, gelme zamanı geldi.':'Durum: '+status.label+'.';else if(parsed.intent==='client_risk')value=status.key==='risk'?'Evet, kaybedilme riski taşıyor.':'Hayır. Durum: '+status.label+'.';else if(parsed.intent==='client_next_visit')value=row.expected_next_visit_date?'Tahmini sonraki geliş: '+friendlyDate(row.expected_next_visit_date):'Bunu hesaplamak için yeterli ziyaret geçmişi yok.';else if(parsed.intent==='client_notes')value=client.note||row.note||'Kayıtlı müşteri notu yok.';else if(parsed.intent==='client_top_service')value=row.preferred_service_name?'En sık hizmet: '+row.preferred_service_name:'Bunu hesaplamak için yeterli ziyaret geçmişi yok.';else if(parsed.intent==='client_preferred_employee'){var employee=profileById(row.preferred_employee_id);value=employee?'Genellikle '+employee.full_name+' çalışanına geliyor.':'Bunu hesaplamak için yeterli ziyaret geçmişi yok.'}
  remember('clients',[row],parsed);render(answer(parsed,'<h3>'+esc(client.full_name)+'</h3><p>'+esc(value)+'</p>'+customerActions(client.id))) }
function contextFollowUp(parsed){if(!session.last||Date.now()-session.last.at>CONTEXT_MS){session.last=null;return false}var n=parsed.normalized,wordCount={bir:1,iki:2,uc:3,dort:4,bes:5},countMatch=n.match(/^(?:ilk\s+)?(\d+|bir|iki|uc|dort|bes)(?:ini)?\s+goster/);if(countMatch){var count=Number(countMatch[1])||wordCount[countMatch[1]],items=session.last.items.slice(0,count);render(session.last.type==='clients'?cards(items,parsed):session.last.type==='appointments'?appointmentCards(items,parsed):slotsHtml(items,parsed));return true}var ordinal={birinci:0,ikinci:1,ucuncu:2,dorduncu:3,besinci:4},key=Object.keys(ordinal).find(function(k){return n.includes(k)});if(key&&/(kart|gecmis)/.test(n)&&session.last.type==='clients'){var row=session.last.items[ordinal[key]];if(row){session.focusedClientId=row.client_id;if(/gecmis/.test(n))assistantOpenHistory(row.client_id);else openCustomerDetail(row.client_id);return true}}if(/riskli olan/.test(n)&&session.last.type==='clients'){var risk=session.last.items.filter(function(r){return statusFor(r).key==='risk'});render(cards(risk,parsed));return true}if(/ilk bosluga uygun/.test(n)&&session.last.type==='slots'){var slot=session.last.items[0],candidates=phaseRows().filter(visibleClient).filter(function(r){var key=statusFor(r).key;return ['approaching','due','overdue','risk'].includes(key)&&(!r.preferred_employee_id||String(r.preferred_employee_id)===String(slot.employeeId))});render(answer(parsed,'<h3>'+candidates.length+' uygun müşteri</h3>'+cards(candidates.slice(0,10),parsed)));return true}return false}
function nearbySlots(date,employeeId,time){var rows=(cache.get('day:'+date)||{}).data||[],profile=profileById(employeeId),target=Number(time.slice(0,2))*60+Number(time.slice(3));return slotGroups(date,rows,[profile],null).flatMap(function(g){var values=[];for(var m=g.start;m<g.end;m+=30)values.push(m);return values}).sort(function(a,b){return Math.abs(a-target)-Math.abs(b-target)}).slice(0,3).map(clock)}
async function futureAppointments(clientId){var q=await salonDb.from('appointments').select('id,client_id,client_name,service_id,service_name,amount,employee_id,scheduled_at,duration_minutes,status,created_by').eq('client_id',clientId).gte('scheduled_at',new Date().toISOString()).neq('status','cancelled').order('scheduled_at').limit(10);if(q.error)throw q.error;return (q.data||[]).map(remoteAppointment)}
function appointmentChoice(rows,parsed){session.ambiguity={parsed:parsed,appointmentIds:rows.map(function(a){return a.id})};render('<div class="assistant-answer"><h3>'+rows.length+' gelecek randevu buldum. Hangisi?</h3>'+rows.map(function(a){return '<button class="assistant-pick" onclick="selectSalonAssistantAppointment('+attr(a.id)+')"><strong>'+esc(a.customer)+' · '+esc(a.time)+'</strong><small>'+esc(friendlyDate(appointmentDate(a)))+' · '+esc(a.staff)+' · '+esc(a.operation)+'</small></button>'}).join('')+'</div>')}
window.selectSalonAssistantAppointment=function(id){if(!session.ambiguity||!session.ambiguity.appointmentIds.map(String).includes(String(id)))return;var parsed=session.ambiguity.parsed;session.ambiguity=null;parsed.appointmentId=id;prepareMutation(parsed)};
function confirmation(action){session.pending=action;var a=action.appointment;render('<div class="assistant-confirm"><h3>Onay gerekli</h3><p><strong>'+esc(a?a.customer:action.client.full_name)+'</strong><br>'+esc(action.summary)+'</p><small>İşlem, yalnızca Onayla düğmesine basınca uygulanır ve kullanıcı kimliği işlem geçmişine yazılır.</small><div class="row"><button class="save" onclick="confirmSalonAssistantAction()">Onayla</button><button class="back" onclick="cancelSalonAssistantAction()">Vazgeç</button></div></div>')}
async function prepareMutation(parsed){var client=await resolveClient(parsed);if(client==='ambiguous')return;if(!client){notice('Kayıt bulunamadı. Müşteri adını biraz daha açık yazın.');return}if(parsed.intent==='create_appointment'){if(!parsed.date||!parsed.time){notice(parsed.time?'Randevu tarihini net anlayamadım. “yarın” veya “28 Ağustos” gibi söyleyin.':'Randevu saatini net anlayamadım. “16:00” veya “dört buçuk” gibi söyleyin.');return}confirmation({type:'create',client:client,date:parsed.date,time:parsed.time,employee:parsed.employee||(!isManager()?profileById(currentUser.id):null),summary:friendlyDate(parsed.date)+' · '+parsed.time+' için randevu formu açılacak.'});return}
  var rows=await futureAppointments(client.id);if(parsed.appointmentId)rows=rows.filter(function(a){return String(a.id)===String(parsed.appointmentId)});if(!rows.length){notice('Değiştirilebilecek gelecek randevu bulunamadı.');return}if(rows.length>1&&!parsed.appointmentId){appointmentChoice(rows,parsed);return}var item=rows[0];if(!canManageOwnAppointment(item)){notice('Bu randevuyu değiştirme yetkiniz yok.');return}var date=parsed.date||appointmentDate(item),time=parsed.time||item.time,employee=parsed.intent==='transfer_appointment'?parsed.employee:null;if(parsed.intent==='transfer_appointment'&&!employee){notice('Hedef çalışanı açıkça yazın.');return}var employeeId=employee?employee.id:item.employeeId,duration=Number(item.duration||30);await dayAppointments(date);if(parsed.intent!=='cancel_appointment'&&appointmentConflictFor(date,time,duration,employeeId,item.id)){var alternatives=nearbySlots(date,employeeId,time);notice((employee?employee.full_name:item.staff)+' '+time+' saatinde dolu.'+(alternatives.length?' Yakın boş saatler: '+alternatives.join(', '):''));return}var summary=parsed.intent==='cancel_appointment'?friendlyDate(appointmentDate(item))+' · '+item.time+' randevusu iptal edilecek.':friendlyDate(appointmentDate(item))+' '+item.time+' → '+friendlyDate(date)+' '+time+(employee?' · Çalışan: '+employee.full_name:'');confirmation({type:parsed.intent,item:item,appointment:item,date:date,time:time,employeeId:employeeId,employeeName:employee?employee.full_name:item.staff,summary:summary})}
window.cancelSalonAssistantAction=function(){session.pending=null;render('<div class="empty">İşlem iptal edildi. Hiçbir kayıt değiştirilmedi.</div>')};
window.confirmSalonAssistantAction=async function(){var action=session.pending;if(!action)return;session.pending=null;try{if(action.type==='create'){openAppointmentModal(action.time,null,action.employee&&action.employee.full_name||'');document.getElementById('appointmentDate').value=action.date;document.getElementById('appointmentCustomer').value=action.client.full_name;if(window.SalonSmartTest&&SalonSmartTest.selectClient)SalonSmartTest.selectClient(action.client.id);if(typeof applyCustomerHistory==='function')applyCustomerHistory(action.client);render('<div class="security">Randevu formu hazırlandı. İşlem ve ücreti kontrol edip kaydedin.</div>');return}var values=action.type==='cancel_appointment'?{status:'cancelled',updated_by:currentUser.id}:{scheduled_at:remoteSchedule(action.date,action.time),employee_id:action.employeeId,updated_by:currentUser.id},q=await salonDb.from('appointments').update(values).eq('id',action.appointment.id).select('id,scheduled_at,employee_id,status');if(q.error||!q.data||q.data.length!==1)throw q.error||new Error('Kayıt güncellenemedi veya yetkiniz yok.');cache.clear();await reloadRemoteData();render('<div class="security">İşlem tamamlandı ve denetim kaydına işlendi.</div>');if(action.type!=='cancel_appointment'&&window.appointmentUpdateNeedsWhatsApp&&appointmentUpdateNeedsWhatsApp(action.appointment,action.employeeId,action.date,action.time,action.employeeName)){var client=clientById(action.appointment.clientId),phone=action.appointment.phone||client&&client.phone;if(phone){var url=whatsappAppointmentUpdateUrl(action.appointment.customer,phone,action.date,action.time,action.employeeName,appointmentRevenue(action.appointment),action.appointment.operation);setTimeout(function(){window.open(url,'_blank','noopener')},20)}}}catch(e){notice(e&&e.message||'İşlem tamamlanamadı.')}};
async function execute(parsed){if(!parsed.intent){if(contextFollowUp(parsed))return;render(suggestionHtml(parsed));return}loading();try{
  if(parsed.employee&&!isManager()&&String(parsed.employee.id)!==String(currentUser.id)){notice('Çalışan hesabıyla yalnızca kendi randevu ve boş saatlerinizi görebilirsiniz.');return}
  if(parsed.intent==='help'){render(helpHtml());return}
  if(parsed.intent==='compare_clients'){var compared=await resolveComparison(parsed);if(compared==='ambiguous')return;if(!compared){notice('Karşılaştırılacak müşterilerden biri bulunamadı.');return}var comparisonRows=phaseRows(),items=compared.map(function(c){return comparisonRows.find(function(r){return String(r.client_id)===String(c.id)})||{client_id:c.id,full_name:c.full_name}});remember('clients',items,parsed);render(answer(parsed,'<h3>Son ziyaret karşılaştırması</h3>'+items.map(function(row,index){return '<div class="assistant-row"><strong>'+esc(compared[index].full_name)+'</strong><small>'+(row.last_visit_date?esc(friendlyDate(row.last_visit_date)):'Kayıt bulunamadı.')+'</small></div>'}).join('')));return}
  if(parsed.intent.startsWith('client_')){await executeClient(parsed);return}
  if(['create_appointment','move_appointment','transfer_appointment','cancel_appointment'].includes(parsed.intent)){if(/^(ona|onun)$/.test(fold(parsed.client))&&session.focusedClientId)parsed.clientId=session.focusedClientId;await prepareMutation(parsed);return}
  if(['due_customers','overdue_customers','risk_customers','inactive_customers','attention_customers','due_this_week','regular_customers','lapsed_customers','risk_candidates'].includes(parsed.intent)){var ar=analysisRows(parsed.intent,parsed);render(answer(parsed,'<h3>'+ar.length+' müşteri bulundu</h3>'+cards(ar,parsed)));return}
  if(parsed.intent==='frequent_customers'){render(answer(parsed,'<h3>Bu ay en çok gelenler</h3>'+await frequentCustomers(parsed)));return}
  if(parsed.intent==='gap_candidates'){var gaps=window.SalonPhase2Test&&SalonPhase2Test.gapSuggestions?SalonPhase2Test.gapSuggestions():[];var clients=[];gaps.forEach(function(g){(g.candidates||[]).forEach(function(r){if(!clients.some(function(x){return String(x.client_id)===String(r.client_id)}))clients.push(r)})});render(answer(parsed,'<h3>Boşluğu doldurabilecek '+clients.length+' müşteri</h3>'+cards(clients,parsed)));return}
  if(['employee_performance','employee_workload'].includes(parsed.intent)&&!isManager()){notice('Bu bilgi yalnızca yönetici yetkisiyle görüntülenebilir.');return}
  if(parsed.intent==='salon_summary'){if(isManager()){var summary=window.SalonPhase2Test&&SalonPhase2Test.summaryMetrics?SalonPhase2Test.summaryMetrics():null;render('<div class="assistant-answer"><h3>Bugünkü salon özeti</h3><p>'+(summary?esc(summary.appointments+' randevu · '+summary.gaps.length+' boşluk · '+(summary.due+summary.overdue)+' zamanı gelen/geciken müşteri · '+summary.risk+' riskli müşteri'):'Özet verisi henüz hazır değil.')+'</p></div>')}else{var personalDate=localDate(0),personalRows=await dayAppointments(personalDate),ownRows=personalRows.filter(function(a){return String(a.employeeId)===String(currentUser.id)}),ownProfile=profileById(currentUser.id),ownSlots=slotGroups(personalDate,ownRows,ownProfile?[ownProfile]:[],null),ownAttention=analysisRows('attention_customers',{limit:50});render('<div class="assistant-answer"><h3>Bugünkü programınız</h3><p>'+ownRows.length+' randevu · '+ownSlots.length+' boşluk · '+ownAttention.length+' ilgilenilecek müşteri</p></div>')}return}
  if(parsed.intent==='employee_performance'){showPage('employeePerformance');return}
  if(parsed.intent==='employee_workload'){var date=parsed.date||localDate(0),work=await dayAppointments(date),counts={};work.forEach(function(a){counts[a.employeeId]=(counts[a.employeeId]||0)+1});var ids=Object.keys(counts).sort(function(a,b){return counts[b]-counts[a]});render(ids.length?'<div class="assistant-answer">'+ids.map(function(id){var p=profileById(id);return '<div class="assistant-row"><strong>'+esc(p?p.full_name:'Çalışan')+'</strong><small>'+counts[id]+' randevu</small></div>'}).join('')+'</div>':'<div class="empty">Kayıt bulunamadı.</div>');return}
  if(parsed.intent==='busiest_day'){var start=localDate(0),end=isoAdd(start,7),rangeQuery=await salonDb.from('appointments').select('scheduled_at,status').gte('scheduled_at',start+'T00:00:00+03:00').lt('scheduled_at',end+'T00:00:00+03:00').neq('status','cancelled');if(rangeQuery.error)throw rangeQuery.error;var dayCounts={};(rangeQuery.data||[]).forEach(function(a){var day=toIstanbul(a.scheduled_at).date;dayCounts[day]=(dayCounts[day]||0)+1});var busiest=Object.keys(dayCounts).sort(function(a,b){return dayCounts[b]-dayCounts[a]})[0];render(busiest?answer(parsed,'<h3>Bu haftanın en yoğun günü</h3><p>'+esc(friendlyDate(busiest))+' · '+dayCounts[busiest]+' randevu</p>'):'<div class="empty">Bu hafta randevu kaydı yok.</div>');return}
  if(['weekly_appointment_count','weekly_free_slots'].includes(parsed.intent)){var week=weekRange(parsed.raw),weekRows=await rangeAppointments(week.start,week.end,{employeeId:parsed.employee&&parsed.employee.id});if(parsed.intent==='weekly_appointment_count'){render(answer(parsed,'<h3>Haftalık randevular</h3><p>'+weekRows.length+' randevu var.</p>'));return}var weekSlots=[];for(var wi=0;wi<7;wi++){var wd=isoAdd(week.start,wi),wr=weekRows.filter(function(a){return appointmentDate(a)===wd});weekSlots=weekSlots.concat(slotGroups(wd,wr,visibleProfiles(parsed),null))}render(answer(parsed,'<h3>Bu haftanın boşlukları</h3>'+slotsHtml(weekSlots,parsed)));return}
  if(parsed.intent==='cancelled_appointments'){var cancelledDate=parsed.date||localDate(0),cancelledRows=await rangeAppointments(cancelledDate,isoAdd(cancelledDate,1),{cancelled:true,employeeId:parsed.employee&&parsed.employee.id});render(answer(parsed,'<h3>'+esc(friendlyDate(cancelledDate))+' iptal edilen randevular</h3>'+appointmentCards(cancelledRows,parsed)));return}
  var date=parsed.date||localDate(0),rows=await dayAppointments(date),profiles=visibleProfiles(parsed);if(parsed.employee)rows=rows.filter(function(a){return String(a.employeeId)===String(parsed.employee.id)});if(!isManager())rows=rows.filter(function(a){return String(a.employeeId)===String(currentUser.id)});
  if(parsed.intent==='appointments'||parsed.intent==='employee_appointments'){if(parsed.after)rows=rows.filter(function(a){return a.time>parsed.after});if(parsed.range)rows=rows.filter(function(a){return a.time>=parsed.range.start&&a.time<parsed.range.end});render(answer(parsed,'<h3>'+esc(friendlyDate(date))+' randevuları</h3>'+appointmentCards(rows,parsed)));return}
  if(parsed.intent==='appointment_count'){render(answer(parsed,'<h3>'+esc(friendlyDate(date))+'</h3><p>'+rows.length+' randevu var.</p>'));return}
  if(parsed.intent==='customer_count'){var unique=new Set(rows.map(function(a){return a.clientId||fold(a.customer)}));render(answer(parsed,'<h3>'+esc(friendlyDate(date))+'</h3><p>'+unique.size+' müşteri var.</p>'));return}
  if(['free_slots','employee_free_slots','who_free','first_free_slot'].includes(parsed.intent)){var slots=slotGroups(date,rows,profiles,parsed.after);if(parsed.intent==='who_free'&&parsed.time){var target=Number(parsed.time.slice(0,2))*60+Number(parsed.time.slice(3));slots=slots.filter(function(s){return s.start<=target&&s.end>target})}if(parsed.intent==='first_free_slot')slots=slots.sort(function(a,b){return a.start-b.start}) .slice(0,1);render(answer(parsed,'<h3>'+esc(friendlyDate(date))+' boş saatler</h3>'+slotsHtml(slots,parsed)));return}
}catch(e){notice(e&&e.message||'Bilgiler getirilemedi.')}}
window.runSalonAssistant=async function(event){if(event&&event.preventDefault)event.preventDefault();var input=document.getElementById('salonAssistantInput'),command=input&&input.value.trim();if(!command)return;await execute(parser(command))};
window.runPhase2HomeAssistant=async function(event){if(event&&event.preventDefault)event.preventDefault();var home=document.getElementById('phase2AssistantInput'),full=document.getElementById('salonAssistantInput');if(!home||!home.value.trim())return;if(full)full.value=home.value.trim();await execute(parser(home.value.trim()))};
window.useAssistantExample=function(button){var text=button.textContent,input=document.getElementById('salonAssistantInput');if(input){input.value=text;input.focus()}};
var legacyRenderBeforeV210=window.render;
window.render=function(){
  // The Phase 2 home deliberately removes the legacy `next` list. The other
  // modern renderers own the home/calendar UI after that point.
  if(!document.getElementById('next'))return;
  return legacyRenderBeforeV210.apply(this,arguments);
};
var oldReload=reloadRemoteData;reloadRemoteData=async function(){cache.clear();return oldReload.apply(this,arguments)};
// Phase 2 replaces the legacy home markup after the first successful login.
// A later login in the same WebView must therefore not write to removed nodes.
var renderHomeSummaryBeforeV201=renderHomeSummary;
renderHomeSummary=function(){
  if(!document.getElementById('todayText')){
    var manager=currentUser&&currentUser.role==='yonetici';
    document.querySelectorAll('.manager-only').forEach(function(node){node.classList.toggle('hidden',!manager)});
    return;
  }
  return renderHomeSummaryBeforeV201.apply(this,arguments);
};
function setLoginNodeText(id,value){var node=document.getElementById(id);if(node)node.textContent=value}
var enterAppBeforeV201=enterApp;
enterApp=function(){
  var auth=document.getElementById('auth'),app=document.getElementById('app');
  if(auth)auth.classList.add('hidden');
  if(app)app.classList.remove('hidden');
  setLoginNodeText('welcomeName',String(currentUser&&currentUser.name||'').split(' ')[0]);
  setLoginNodeText('accountName',currentUser&&currentUser.name||'—');
  setLoginNodeText('accountRole',currentUser&&currentUser.role==='yonetici'?'Yönetici hesabı':'Personel hesabı');
  var manager=!!(currentUser&&currentUser.role==='yonetici'),adminControls=document.getElementById('adminControls');
  if(adminControls)adminControls.classList.toggle('hidden',!manager);
  document.querySelectorAll('.manager-menu').forEach(function(node){node.classList.toggle('hidden',!manager)});
  var navButtons=document.querySelectorAll('.nav button');
  if(navButtons[2])navButtons[2].classList.toggle('hidden',!manager);
  if(navButtons[3])navButtons[3].classList.toggle('hidden',!manager);
  var actions=document.querySelectorAll('.actions .action');
  if(actions[1])actions[1].classList.toggle('hidden',!manager);
  if(actions[2])actions[2].classList.toggle('hidden',!manager);
  var kindOptions=document.querySelectorAll('#kind option'),kind=document.getElementById('kind');
  if(kindOptions[1])kindOptions[1].hidden=!manager;
  if(kindOptions[2])kindOptions[2].hidden=!manager;
  if(!manager&&kind)kind.value='İşlem';
  renderHomeSummary();
  if(typeof window.render==='function')window.render();
  if(typeof renderUsers==='function')renderUsers();
  if(typeof renderCalendar==='function')renderCalendar();
  if(typeof renderStatistics==='function')renderStatistics();
  showPage('home');
};
function timed(promise,ms,message){var timer;return Promise.race([promise,new Promise(function(_,reject){timer=setTimeout(function(){reject(new Error(message))},ms)})]).finally(function(){clearTimeout(timer)})}
var loginBeforeV2=login;
login=async function(event){if(event&&event.preventDefault)event.preventDefault();var form=event&&event.currentTarget||document.getElementById('loginForm'),button=form&&form.querySelector('button.save'),username=normalizeLoginName(document.getElementById('loginUsername')?.value||''),password=document.getElementById('loginPassword')?.value||'';if(!username||!password){remoteError('Kullanıcı adı ve şifreyi yazın.');return}if(button){button.disabled=true;button.textContent='Giriş yapılıyor…'}try{var result=await timed(salonDb.auth.signInWithPassword({email:username+'@salon-modern.local',password:password}),15000,'Sunucu yanıt vermedi. İnternet bağlantınızı kontrol edin.');if(result.error)throw result.error;localStorage.setItem('salonModernRememberSessionV1','true');localStorage.setItem('salonModernRememberUsernameV1',username);localStorage.removeItem('salonModernExplicitLogoutV1');await timed(loadRemoteSession(),25000,'Hesap açıldı ancak salon verileri zamanında yüklenemedi. Tekrar deneyin.')}catch(error){setRemoteAuth(false);var message=/invalid login|invalid credentials/i.test(error&&error.message||'')?'Kullanıcı adı veya şifre hatalı. Yönetici, çalışan kartından yeni şifre belirleyebilir.':error&&error.message||'Giriş tamamlanamadı.';remoteError(message)}finally{if(button){button.disabled=false;button.textContent='Giriş yap'}}};
var startBeforeV2=startRemoteApp;
startRemoteApp=async function(){var auth=document.getElementById('auth'),loginForm=document.getElementById('loginForm'),setup=document.getElementById('setupForm'),sessionFound=false;if(setup)setup.classList.add('hidden');if(auth)auth.classList.remove('hidden');if(loginForm)loginForm.classList.add('hidden');try{var sessionResult=await timed(salonDb.auth.getSession(),8000,'Kayıtlı oturum kontrolü zaman aşımına uğradı.');if(sessionResult.error)throw sessionResult.error;sessionFound=Boolean(sessionResult.data&&sessionResult.data.session);if(sessionFound){await timed(loadRemoteSession(),25000,'Salon verileri zamanında yüklenemedi.');return}}catch(error){remoteError(error&&error.message||'Kayıtlı oturum açılamadı.');if(sessionFound)return}setRemoteAuth(false);installPersistentLoginTheme()};
var style=document.createElement('style');style.textContent='.assistant-result-card{padding:12px;margin:8px 0;border:1px solid var(--line);border-radius:14px;background:#fff}.assistant-result-card>strong,.assistant-result-card>small{display:block}.assistant-result-card>small{margin-top:5px;color:var(--muted);line-height:1.45}.assistant-actions{display:flex;gap:6px;overflow:auto;margin-top:9px}.assistant-actions button,.assistant-pick,.assistant-help button{border:1px solid var(--line);border-radius:10px;background:#f8f5ef;padding:8px;font-weight:700}.assistant-pick{display:block;width:100%;text-align:left;margin:7px 0}.assistant-pick strong,.assistant-pick small{display:block}.assistant-pick small{margin-top:4px;color:var(--muted)}.assistant-help strong{display:block;margin-top:12px}.assistant-help button{display:block;width:100%;text-align:left;margin-top:5px}.assistant-understood{margin-bottom:10px;padding:8px 10px;border-radius:10px;background:#eef6f2;color:#315b4d;font-size:12px}.assistant-understood strong{color:#173d32}';document.head.appendChild(style);
window.SalonAssistantV2Test={fold:fold,normalizeCommand:normalizeCommand,normalizeLoginName:normalizeLoginName,parse:parser,extractEntities:extractEntities,parseDate:parseDate,parseTime:parseTime,parseTimeRange:parseTimeRange,weekRange:weekRange,statusFor:statusFor,matchingClients:matchingClients,suggestions:commandSuggestions,getSession:function(){return session},resetSession:function(){session={last:null,pending:null,ambiguity:null,focusedClientId:null,focusedEmployeeId:null,focusedDate:null,focusedSlot:null};cache.clear()},clearCache:function(){cache.clear()},timed:timed};
document.querySelectorAll('#appVersion').forEach(function(n){n.textContent='v'+VERSION});document.querySelectorAll('.auth small').forEach(function(n){if(/^v\d/.test(n.textContent))n.textContent='v'+VERSION});
})();
