(function(){
'use strict';
var VERSION='2.2.0';
var voice={targetId:null,active:false,lastText:'',webRecognition:null,installTimer:null};

function esc(value){return String(value||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function inputFor(id){return document.getElementById(id||voice.targetId||'phase2AssistantInput')||document.getElementById('salonAssistantInput')}
function statusFor(id){return document.getElementById((id||voice.targetId||'phase2AssistantInput')+'VoiceStatus')}
function errorMessage(code){var messages={permission_denied:'Sesli komut için mikrofon izni gerekiyor. Yazılı Salon Asistanını kullanmaya devam edebilirsiniz.',unsupported:'Bu cihazda ücretsiz yerleşik ses tanıma desteklenmiyor. Yazılı Salon Asistanı normal şekilde kullanılabilir.',network:'Cihazın ses tanıma servisi bağlantı kuramadı. İnternet bağlantısını kontrol edin veya komutu yazın.',no_match:'Sizi net duyamadım. Tekrar deneyebilirsiniz.',busy:'Mikrofon şu anda meşgul. Birkaç saniye sonra tekrar deneyin.',audio:'Mikrofon sesi alınamadı. Mikrofonu kontrol edip tekrar deneyin.',service:'Cihazın ses tanıma servisi başlatılamadı. Komutu yazarak devam edebilirsiniz.',unknown:'Sesli komut tamamlanamadı. Yazılı Salon Asistanını kullanabilirsiniz.'};return messages[code]||messages.unknown}
function setPanel(id,html,state){var panel=statusFor(id);if(!panel)return;panel.className='salon-voice-status'+(state?' '+state:'');panel.innerHTML=html;panel.classList.remove('hidden')}
function setSimpleState(state,detail){var id=voice.targetId,panel=statusFor(id);if(!panel)return;if(state==='starting'||state==='listening'||state==='hearing'){voice.active=true;setPanel(id,'<div class="salon-voice-listening"><span class="salon-voice-pulse">🎤</span><div><strong>Dinliyorum...</strong><small>Kısa ve net bir salon komutu söyleyin.</small></div></div><button type="button" class="salon-voice-cancel" data-voice-cancel>Durdur</button>','listening');var cancel=panel.querySelector('[data-voice-cancel]');if(cancel)cancel.onclick=function(){window.cancelSalonVoice()};return}if(state==='processing'){setPanel(id,'<div class="salon-voice-listening"><span>⌛</span><div><strong>Ses işleniyor...</strong><small>Algılanan metin birazdan görünecek.</small></div></div>','processing');return}if(state==='permission_required'){setPanel(id,'<div class="notice">Mikrofon izni isteniyor. İzin verirseniz konuşmaya başlayabilirsiniz.</div>','');return}if(state==='cancelled'){voice.active=false;if(panel)panel.classList.add('hidden');return}if(state==='unsupported'){voice.active=false;setPanel(id,'<div class="notice">'+esc(errorMessage('unsupported'))+'</div>','error');return}if(state==='permission_denied'||state==='error'){voice.active=false;setPanel(id,'<div class="notice">'+esc(errorMessage(state==='error'?detail:state))+'</div><button type="button" class="back" data-voice-retry>Tekrar Dene</button>','error');var retry=panel.querySelector('[data-voice-retry]');if(retry)retry.onclick=function(){window.startSalonVoice(id)}}
}
function nativeAvailable(){try{return !!(window.SalonAndroid&&typeof window.SalonAndroid.startSpeechRecognition==='function')}catch(error){return false}}
function recognizedPanel(id,text){setPanel(id,'<div class="salon-voice-understood"><small>Şunu anladım:</small><strong>'+esc(text)+'</strong></div><div class="salon-voice-actions"><button type="button" class="save" data-voice-run>Çalıştır</button><button type="button" class="back" data-voice-edit>Düzenle</button><button type="button" class="back" data-voice-retry>Tekrar Konuş</button></div>','recognized');var panel=statusFor(id),run=panel&&panel.querySelector('[data-voice-run]'),edit=panel&&panel.querySelector('[data-voice-edit]'),retry=panel&&panel.querySelector('[data-voice-retry]');if(run)run.onclick=function(){window.runSalonVoiceCommand()};if(edit)edit.onclick=function(){window.editSalonVoiceCommand()};if(retry)retry.onclick=function(){window.startSalonVoice(id)}}
function installFor(input){if(!input||document.getElementById(input.id+'VoiceControls'))return;var form=input.closest('form');if(!form)return;var controls=document.createElement('div');controls.id=input.id+'VoiceControls';controls.className='salon-voice-controls';controls.innerHTML='<button type="button" class="salon-voice-primary" data-voice-start><span>🎤</span> Konuş</button><button type="button" class="salon-write-primary" data-voice-write><span>⌨️</span> Yaz</button>';var start=controls.querySelector('[data-voice-start]'),write=controls.querySelector('[data-voice-write]');if(start)start.onclick=function(){window.startSalonVoice(input.id)};if(write)write.onclick=function(){window.focusSalonAssistantInput(input.id)};form.insertBefore(controls,form.firstChild);var status=document.createElement('div');status.id=input.id+'VoiceStatus';status.className='salon-voice-status hidden';status.setAttribute('aria-live','polite');form.insertBefore(status,controls.nextSibling);input.addEventListener('input',function(){if(voice.targetId===input.id&&voice.lastText&&input.value!==voice.lastText){var panel=statusFor(input.id);if(panel&&panel.classList.contains('recognized'))panel.classList.add('edited')}})}
function install(){var appVersion=window.SALON_APP_VERSION||VERSION;installFor(document.getElementById('phase2AssistantInput'));installFor(document.getElementById('salonAssistantInput'));document.querySelectorAll('.phase2-chips button:nth-child(n+5)').forEach(function(button){button.classList.add('hidden')});document.querySelectorAll('#appVersion').forEach(function(node){node.textContent='v'+appVersion});document.querySelectorAll('.auth small').forEach(function(node){if(/^v\d/.test(node.textContent))node.textContent='v'+appVersion})}

window.focusSalonAssistantInput=function(id){var input=inputFor(id);if(input){input.focus();if(input.scrollIntoView)input.scrollIntoView({block:'center',behavior:'smooth'})}};
window.startSalonVoice=function(id){voice.targetId=id||(document.getElementById('phase2AssistantInput')?'phase2AssistantInput':'salonAssistantInput');voice.lastText='';install();if(!nativeAvailable()){setSimpleState('unsupported','');return}setSimpleState('starting','');try{window.SalonAndroid.startSpeechRecognition()}catch(error){setSimpleState('error','service')}};
window.cancelSalonVoice=function(){try{if(window.SalonAndroid&&window.SalonAndroid.cancelSpeechRecognition)window.SalonAndroid.cancelSpeechRecognition()}catch(error){}voice.active=false;setSimpleState('cancelled','')};
window.onSalonVoiceState=function(state,detail){setSimpleState(state,detail||'')};
window.onSalonVoicePartial=function(text){var input=inputFor();if(!input||!text)return;input.value=text;setPanel(voice.targetId,'<div class="salon-voice-listening"><span class="salon-voice-pulse">🎤</span><div><strong>Dinliyorum...</strong><small>'+esc(text)+'</small></div></div><button type="button" class="salon-voice-cancel" data-voice-cancel>Durdur</button>','listening');var panel=statusFor(),cancel=panel&&panel.querySelector('[data-voice-cancel]');if(cancel)cancel.onclick=function(){window.cancelSalonVoice()}};
window.onSalonVoiceResult=function(text){voice.active=false;voice.lastText=String(text||'').trim();var input=inputFor();if(!input||!voice.lastText){setSimpleState('error','no_match');return}input.value=voice.lastText;recognizedPanel(voice.targetId,voice.lastText)};
window.editSalonVoiceCommand=function(){var input=inputFor();if(input){input.focus();input.setSelectionRange(input.value.length,input.value.length)}var panel=statusFor();if(panel)panel.classList.add('edited')};
window.runSalonVoiceCommand=async function(){var input=inputFor(),command=input&&input.value.trim();if(!command)return;voice.lastText=command;window.salonAssistantCommandSource='voice_assistant';var full=document.getElementById('salonAssistantInput');if(full)full.value=command;try{if(input.id==='phase2AssistantInput'&&window.runPhase2HomeAssistant)await window.runPhase2HomeAssistant({preventDefault:function(){}});else if(window.runSalonAssistant)await window.runSalonAssistant({preventDefault:function(){}})}finally{window.salonAssistantCommandSource=null}}

var showPageBeforeVoice=window.showPage;window.showPage=function(id){var value=showPageBeforeVoice.apply(this,arguments);setTimeout(install,0);return value};
if(window.MutationObserver){new MutationObserver(function(){clearTimeout(voice.installTimer);voice.installTimer=setTimeout(install,20)}).observe(document.body,{childList:true,subtree:true})}
var style=document.createElement('style');style.textContent='.salon-voice-controls{display:grid;grid-template-columns:1.35fr 1fr;gap:10px;margin:12px 0}.salon-voice-controls button{min-height:54px;border-radius:15px;border:1px solid var(--line);font-size:16px;font-weight:800}.salon-voice-primary{background:#111;color:#fff;border-color:#111!important}.salon-voice-primary span{font-size:21px}.salon-write-primary{background:#f7f4ed;color:#222}.salon-voice-status{margin:10px 0 12px;padding:13px;border:1px solid var(--line);border-radius:14px;background:#fbfaf7}.salon-voice-listening{display:flex;align-items:center;gap:11px}.salon-voice-listening strong,.salon-voice-listening small,.salon-voice-understood small,.salon-voice-understood strong{display:block}.salon-voice-listening small,.salon-voice-understood small{margin-top:3px;color:var(--muted)}.salon-voice-pulse{display:grid;place-items:center;width:42px;height:42px;border-radius:50%;background:#f5e7da;animation:salonVoicePulse 1.15s infinite}.salon-voice-cancel{margin-top:10px;border:0;background:transparent;color:#a34f48;font-weight:800}.salon-voice-understood strong{margin-top:5px;line-height:1.45}.salon-voice-actions{display:flex;gap:7px;margin-top:11px}.salon-voice-actions button{flex:1;min-height:42px;margin:0;padding:9px 6px}.salon-voice-status.edited{border-color:#bf8d48}.salon-voice-status.error{background:#fff8f6}@keyframes salonVoicePulse{0%,100%{box-shadow:0 0 0 0 #bd8b4e55}50%{box-shadow:0 0 0 10px #bd8b4e00}}@media(max-width:380px){.salon-voice-actions{flex-wrap:wrap}.salon-voice-actions button{flex:1 1 45%}}';document.head.appendChild(style);
window.SalonVoiceTest={errorMessage:errorMessage,nativeAvailable:nativeAvailable,getState:function(){return voice},install:install};
install();
})();
