(function(){
  'use strict';
  var defaults={
    instagram_url:'https://www.instagram.com/salonmodernn/',
    google_maps_url:'https://www.google.com/maps/dir/?api=1&destination=Salon+Modern%2C+Bat%C4%B1kent+K%C3%BCr%C5%9Fat+T%C3%BCzmen+Bulvar%C4%B1%2C+9024.+Sk.%2C+%C5%9Eehitkamil%2FGaziantep',
    google_review_url:'https://g.page/r/CXLi6ZostkeBEBM/review',appointment_reminder_minutes:60,
    whatsapp_thank_you_enabled:false,whatsapp_thank_you_delay_minutes:120
  },settings=Object.assign({},defaults);
  function user(){return typeof currentUser!=='undefined'?currentUser:null}
  Object.assign(window.whatsappTemplateConfig,{
    appointment_confirmation:{title:'Yeni randevu onayı',allowed:['{musteri_adi}','{randevu_tarihi}','{randevu_saati}','{islem_adi}','{calisan_adi}','{google_haritalar_url}'],content:'Merhaba {musteri_adi} 👋\n\n💈 Salon Modern randevunuz oluşturuldu.\n\n📅 Tarih: {randevu_tarihi}\n🕒 Saat: {randevu_saati}\n✂️ Hizmet: {islem_adi}\n👤 Berber: {calisan_adi}\n\n📍 Salonumuza yol tarifi:\n{google_haritalar_url}\n\nSizi bekliyoruz.\n\nSalon Modern'},
    appointment_reminder:{title:'1 saatlik randevu hatırlatması',allowed:['{musteri_adi}','{randevu_tarihi}','{randevu_saati}','{calisan_adi}','{google_haritalar_url}'],content:'Merhaba {musteri_adi} 👋\n\n⏰ Salon Modern randevunuzu hatırlatmak isteriz.\n\nRandevunuza yaklaşık 1 saat kaldı.\n\n📅 Tarih: {randevu_tarihi}\n🕒 Saat: {randevu_saati}\n👤 Berber: {calisan_adi}\n\n📍 Yol tarifi:\n{google_haritalar_url}\n\nGörüşmek üzere! 💈'},
    appointment_thank_you:{title:'Randevu sonrası teşekkür',allowed:['{musteri_adi}','{google_yorum_url}','{instagram_url}'],content:'Merhaba {musteri_adi} 👋\n\n💈 Bugün Salon Modern\'i tercih ettiğiniz için teşekkür ederiz.\n\nMemnuniyetiniz bizim için çok değerli.\n\n⭐ Deneyiminizi Google\'da paylaşabilirsiniz:\n{google_yorum_url}\n\n📸 Instagram\'da bizi takip edebilirsiniz:\n{instagram_url}\n\nTekrar görüşmek dileğiyle.\n\nSalon Modern ✂️'}
  });
  Object.keys(window.whatsappTemplateConfig).forEach(function(key){if(!window.salonMessageTemplates[key])window.salonMessageTemplates[key]={template_key:key,title:window.whatsappTemplateConfig[key].title,content:window.whatsappTemplateConfig[key].content}});
  var priorValues=window.appointmentTemplateValues;
  window.appointmentTemplateValues=function(customer,date,time,staffName,amount,operation){return Object.assign(priorValues(customer,date,time,staffName,amount,operation),{'{google_haritalar_url}':settings.google_maps_url,'{google_yorum_url}':settings.google_review_url,'{instagram_url}':settings.instagram_url})};
  window.whatsappAppointmentUrl=function(customer,phone,date,time,staffName,amount,operation){return 'https://wa.me/'+window.whatsappPhone(phone)+'?text='+encodeURIComponent(window.renderSavedTemplate('appointment_confirmation',window.appointmentTemplateValues(customer,date,time,staffName,amount,operation)))};
  var priorAutoKey=window.metaTemplateAutoKey;
  window.metaTemplateAutoKey=function(key){return key==='appointment_thank_you'||priorAutoKey(key)};
  function sampleValues(){return window.appointmentTemplateValues('Ayşe Yılmaz','2026-10-12','14:30','Halil Kıv',500,'Saç kesimi')}
  window.previewMessageTemplate=function(key){var node=document.getElementById('messageTemplatePreview_'+key),input=document.getElementById('messageTemplate_'+key);if(!node||!input)return;var content=input.value;Object.entries(sampleValues()).forEach(function(entry){content=content.split(entry[0]).join(entry[1])});node.textContent=content;node.classList.remove('hidden')};
  var priorCard=window.messageTemplateCard;
  window.messageTemplateCard=function(key){var card=priorCard(key),at=card.lastIndexOf('</div>');return at<0?card:card.slice(0,at)+'<button type="button" class="link" onclick="previewMessageTemplate('+window.jsAttr(key)+')">Önizle</button><pre class="notice hidden" id="messageTemplatePreview_'+key+'" style="white-space:pre-wrap"></pre>'+card.slice(at)};
  function approvedThankYou(){var row=window.salonMetaTemplateMappings.appointment_thank_you;return Boolean(row&&row.approval_status==='approved'&&row.approved_content_hash)}
  function settingsHtml(){var approved=approvedThankYou();return '<div class="message-template-card"><div class="section"><h2>Mesaj bağlantıları ve otomasyon</h2><span class="role">YÖNETİM</span></div><label class="field">Instagram profil URL\'si<input id="messageInstagramUrl" type="url" value="'+window.safe(settings.instagram_url)+'"></label><label class="field">Google Haritalar yol tarifi URL\'si<input id="messageMapsUrl" type="url" value="'+window.safe(settings.google_maps_url)+'"></label><label class="field">Google yorum URL\'si<input id="messageReviewUrl" type="url" value="'+window.safe(settings.google_review_url)+'"></label><label class="field">Hatırlatma süresi (dakika)<input id="messageReminderMinutes" type="number" min="15" max="1440" value="'+Number(settings.appointment_reminder_minutes)+'"></label><label class="field">Teşekkür mesajı gecikmesi<select id="messageThankYouDelay"><option value="60">1 saat</option><option value="120">2 saat</option><option value="180">3 saat</option><option value="1440">24 saat</option></select></label><label class="field"><span><input id="messageThankYouEnabled" type="checkbox" '+(settings.whatsapp_thank_you_enabled?'checked ':'')+(!approved?'disabled ':'')+'> Otomatik teşekkür mesajını aç</span></label><small class="template-help">Pazarlama izni zorunludur. İzin vermeyen veya vazgeçen müşterilere gönderilmez.</small><div class="meta-template-status">'+(approved?'Meta şablonu onaylı. Gönderim ayarı açılabilir.':'Meta onayı bekleniyor · Otomatik teşekkür mesajı kapalıdır.')+'</div><button type="button" class="fab" onclick="saveWhatsappMessageSettings()">Ayarları kaydet</button></div>'}
  function renderAdmin(){var area=document.getElementById('messageTemplateAdmin');if(!area)return;area.innerHTML=settingsHtml()+'<div class="section"><h2>Mesaj Şablonları</h2><span class="role">YÖNETİM</span></div>'+['appointment_confirmation','appointment_update','appointment_reminder','appointment_cancelled','appointment_thank_you','customer_return_reminder'].map(window.messageTemplateCard).join('');var delay=document.getElementById('messageThankYouDelay');if(delay)delay.value=String(settings.whatsapp_thank_you_delay_minutes);window.loadMetaTemplateMappings()}
  var priorInstall=window.installCustomerReturnTools;
  window.installCustomerReturnTools=function(){priorInstall();renderAdmin()};
  async function loadSettings(){if(!user())return;var result=await window.salonDb.from('booking_settings').select('instagram_url,google_maps_url,google_review_url,appointment_reminder_minutes,whatsapp_thank_you_enabled,whatsapp_thank_you_delay_minutes').eq('id',true).maybeSingle();if(!result.error&&result.data)settings=Object.assign({},defaults,result.data)}
  window.saveWhatsappMessageSettings=async function(){var actor=user();if(actor?.role!=='yonetici')return;var next={instagram_url:document.getElementById('messageInstagramUrl').value.trim(),google_maps_url:document.getElementById('messageMapsUrl').value.trim(),google_review_url:document.getElementById('messageReviewUrl').value.trim(),appointment_reminder_minutes:Number(document.getElementById('messageReminderMinutes').value),whatsapp_thank_you_enabled:document.getElementById('messageThankYouEnabled').checked,whatsapp_thank_you_delay_minutes:Number(document.getElementById('messageThankYouDelay').value),updated_by:actor.id,updated_at:new Date().toISOString()};if(![next.instagram_url,next.google_maps_url,next.google_review_url].every(function(value){try{return new URL(value).protocol==='https:'}catch{return false}})){window.showAppToast('Ayarlar kaydedilemedi','Bağlantılar geçerli HTTPS adresleri olmalıdır.');return}if(next.whatsapp_thank_you_enabled&&!approvedThankYou()){window.showAppToast('Ayarlar kaydedilemedi','Teşekkür mesajı Meta tarafından onaylanmadan otomatik gönderim açılamaz.');return}var result=await window.salonDb.from('booking_settings').update(next).eq('id',true).select('*').single();if(result.error){window.showAppToast('Ayarlar kaydedilemedi',result.error.message);return}settings=Object.assign(settings,result.data);window.showAppToast('Mesaj ayarları kaydedildi','Yeni mesajlar güncel ayarları kullanacak.')};
  var priorLoad=window.loadV1526Templates;
  window.loadV1526Templates=async function(){await loadSettings();await priorLoad();if(user()?.role==='yonetici'&&document.getElementById('messageTemplateAdmin'))renderAdmin()};
  var priorSave=window.saveMessageTemplate;
  window.saveMessageTemplate=async function(key){var input=document.getElementById('messageTemplate_'+key),content=input?.value.trim()||'',actor=user();await priorSave(key);if(actor&&window.metaTemplateAutoKey(key)&&window.salonMessageTemplates[key]?.content===content){await window.salonDb.from('whatsapp_meta_template_mappings').update({approval_status:'pending',updated_by:actor.id,updated_at:new Date().toISOString()}).eq('template_key',key);if(window.salonMetaTemplateMappings[key])window.salonMetaTemplateMappings[key].approval_status='pending';var status=document.getElementById('metaTemplateStatus_'+key);if(status)status.textContent=window.metaApprovalLabel(key)}};
})();
