const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('appointment-list-management-2.4.4.js','utf8');
const elems={managedAppointments:{classList:{contains:()=>true},remove(){}},managedList:{innerHTML:'',querySelectorAll:()=>[]},app:{appendChild(){}}};
let records=[],calls=[],fetches=[],failure=null,pending=null,opened=null,deleted=null;
const actor={id:'employee1',role:'calisan'};
const ctx={currentUser:actor,appts:[{id:'existing'}],Intl,Date,Set,console,fetch:async(url,options)=>{fetches.push({url,options});return {ok:true,json:async()=>({sourceAppointmentIds:['online1']})}},document:{getElementById:id=>elems[id],querySelector:()=>null},enterApp(){},showPage(){},reloadRemoteData:async()=>{},closeAppointmentModal(){},closeAppointmentDeleteModal(){},logout(){},canManageOwnAppointment:item=>ctx.currentUser.role==='yonetici'||item.employeeId===ctx.currentUser.id,openAppointmentModal:(time,id,staff)=>opened={time,id,staff},requestAppointmentDeletion:id=>deleted=id,remoteAppointment:r=>({id:r.id,customer:r.client_name,operation:r.service_name,employeeId:r.employee_id,staff:r.employee_id,date:r.scheduled_at.slice(0,10),time:'10:00',amount:r.amount}),salonDb:{auth:{getSession:async()=>({data:{session:{access_token:'test-only'}}})},from(table){assert.equal(table,'appointments');const query={select(){return this},gte(k,v){calls.push({op:'gte',v});return this},lt(k,v){calls.push({op:'lt',v});return this},neq(){return this},order(){return this},eq(k,v){calls.push({op:'eq',k,v});return this},range(start,end){calls.push({op:'range',start,end});if(pending)return pending;return Promise.resolve({data:records.slice(start,end+1),error:failure})}};return query}}};
ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source,ctx);
const api=ctx.SalonAppointmentList;
const row=(id,employee='employee1')=>({id,employee_id:employee,client_name:'Test <client>',service_name:'Service',scheduled_at:'2026-10-01T10:00:00+03:00',amount:500,duration_minutes:45});
(async()=>{
 api.filter.period='range';api.filter.start='2026-12-31';api.filter.end='2027-01-01';assert.equal(api.dates().end,'2027-01-01');
 api.filter.start='2026-02-30';assert.throws(api.dates,/kontrol/);api.filter.start='2026-12-31';
 records=[row('online1'),row('staff1'),row('other','employee2')];await api.load();
 assert(calls.some(x=>x.op==='eq'&&x.k==='employee_id'&&x.v==='employee1'));
 assert.match(elems.managedList.innerHTML,/Online/);assert.match(elems.managedList.innerHTML,/Personel/);assert.match(elems.managedList.innerHTML,/Test &lt;client&gt;/);assert.match(elems.managedList.innerHTML,/2 randevu/);
 assert(!decodeURIComponent(fetches[0].url).includes('other'));
 assert.deepEqual(ctx.appts,[{id:'existing'}],'Listing must never overwrite the calendar state');
 api.filter.source='online';await api.load();assert.match(elems.managedList.innerHTML,/1 randevu/);assert.doesNotMatch(elems.managedList.innerHTML,/Personel/);
 ctx.remoteProfiles=[{id:'creator1',full_name:'Ekleyen Test <Ad>'}];records=[{...row('staffCreator'),created_by:'creator1'},row('unknownCreator')];api.filter.source='staff';await api.load();assert.match(elems.managedList.innerHTML,/Ekleyen: Ekleyen Test &lt;Ad&gt;/);assert.match(elems.managedList.innerHTML,/Ekleyen: Belirtilmemiş/);
 records=[row('online1'),row('staff1'),row('other','employee2')];
 assert.equal(api.permitted({employeeId:'employee2'}),false);
 ctx.currentUser={id:'manager1',role:'yonetici'};calls=[];api.filter.source='all';await api.load();assert(!calls.some(x=>x.op==='eq'));assert.match(elems.managedList.innerHTML,/3 randevu/);
 let editButtons=[],deleteButtons=[];elems.managedList.querySelectorAll=selector=>selector==='[data-edit]'?editButtons:deleteButtons;
 editButtons=[{dataset:{edit:'0'}}];deleteButtons=[{dataset:{delete:'0'}}];await api.load();editButtons[0].onclick();assert.equal(opened.id,'online1');assert.equal(ctx.appts.length,2);ctx.closeAppointmentModal();assert.equal(ctx.appts.length,1);
 deleteButtons[0].onclick();assert.equal(deleted,'online1','Management delete must delegate to existing confirmation');ctx.closeAppointmentDeleteModal();assert.equal(ctx.appts.length,1);
 records=Array.from({length:501},(_,i)=>row('item'+i));calls=[];await api.load();assert.equal(calls.filter(x=>x.op==='range').length,2);assert.match(elems.managedList.innerHTML,/501 randevu/);
 let resolveOld;pending=new Promise(resolve=>resolveOld=resolve);const old=api.load();pending=null;records=[row('latest')];await api.load();resolveOld({data:[row('stale')]});await old;assert.match(elems.managedList.innerHTML,/1 randevu/);assert.doesNotMatch(elems.managedList.innerHTML,/stale/);
 failure={message:'TEST_LOAD_ERROR'};await api.load();assert.match(elems.managedList.innerHTML,/TEST_LOAD_ERROR/);failure=null;
 ctx.logout();ctx.currentUser=null;const before=calls.length;await api.load();assert.equal(calls.length,before);
assert.match(fs.readFileSync('salon-modern.html','utf8'),/appointment-list-management-2\.4\.4\.js\?v=91/);
 assert.match(source,/window.toggleDrawer=function\(\)\{ensure\(\)/,'Install the menu even when session restoration skips the enter wrapper');
 const adminAnchor={id:'admin'},oldRequest={remove(){this.removed=true}};elems.drawerBookingRequests=oldRequest;
 let positioned=null;const drawer={querySelector:()=>adminAnchor,insertBefore(button,anchor){elems[button.id]=button;positioned=anchor}};
 ctx.document.querySelector=()=>drawer;ctx.document.createElement=()=>({});ctx.currentUser=actor;ctx.toggleDrawer=function(){};
 await api.load();assert.equal(positioned,adminAnchor);assert.equal(oldRequest.removed,true);assert.equal(elems.drawerManagedAppointments.textContent,'▤  Randevu Yönetimi');
 assert.doesNotMatch(fs.readFileSync('booking-requests-admin-2.4.0.js','utf8'),/button.id='drawerBookingRequests'/,'Request menu must not be recreated');
 console.log('PASS appointment management dates, sources, employee isolation, edit/delete delegation, pagination, stale responses, logout and replacement menu position');
})().catch(error=>{console.error(error);process.exitCode=1});
