// Isolated local PostgreSQL only. Requires embedded-postgres and pg in a temp runtime.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),os=require('node:os');
const runtime=process.argv[2];if(!runtime)throw Error('Supply local test dependency directory');
const {Client}=require(path.join(runtime,'pg'));
const migration=fs.readFileSync('supabase/migrations/20261001190813_calendar_real_duration_customer_management.sql','utf8');
const fixture=`create extension btree_gist; create schema private; create schema auth;
create role anon;create role authenticated;create role service_role;
create function auth.role() returns text language sql as 'select current_setting(''test.role'',true)';
create function auth.uid() returns uuid language sql as 'select nullif(current_setting(''test.uid'',true),'''')::uuid';
create table services(id uuid primary key,name text,price numeric,duration_minutes integer constraint services_duration_minutes_check check(duration_minutes between 15 and 120 and duration_minutes%15=0),active boolean);
create table profiles(id uuid primary key,full_name text,username text,active boolean,role text);
create table booking_settings(id boolean,online_booking_enabled boolean,default_open_time time,default_close_time time);
create table booking_schedule_overrides(schedule_date date,open_time time,close_time time,is_closed boolean);
create table clients(id uuid primary key default gen_random_uuid(),full_name text,phone text);
create table appointments(id uuid primary key default gen_random_uuid(),client_id uuid,client_name text,client_phone text,service_id uuid,service_name text,amount numeric,employee_id uuid,scheduled_at timestamptz,scheduled_end timestamptz,duration_minutes integer constraint appointments_duration_minutes_check check(duration_minutes between 15 and 120 and duration_minutes%15=0),note text,status text,source text,created_by uuid,updated_by uuid);
create table closed_time_slots(employee_id uuid,starts_at timestamptz,ends_at timestamptz);
create table online_booking_requests(id uuid primary key default gen_random_uuid(),client_name text,phone text,phone_normalized text,service_id uuid,service_name text,amount numeric,employee_id uuid,scheduled_at timestamptz,duration_minutes integer constraint online_booking_requests_duration_minutes_check check(duration_minutes between 15 and 120),note text,request_ip_hash text,public_token uuid unique,status text constraint online_booking_requests_status_check check(status in ('pending','approved','rejected')),appointment_id uuid,reviewed_at timestamptz,created_at timestamptz default now());
create table notifications(recipient_id uuid,appointment_id uuid,kind text,title text,body text);
create function set_appointment_end() returns trigger language plpgsql as $$begin new.scheduled_end:=new.scheduled_at+make_interval(mins=>new.duration_minutes);return new;end$$;
create trigger trg_set_appointment_end before insert or update of scheduled_at,duration_minutes on appointments for each row execute function set_appointment_end();
alter table appointments add constraint appointments_no_overlap exclude using gist(employee_id with =,tstzrange(scheduled_at,scheduled_end,'[)') with &&) where(status<>'cancelled' and source='online');
create function private.reject_appointment_during_closed_time() returns trigger language plpgsql as $$begin return new;end$$;
create trigger appointments_validate_schedule before insert on appointments for each row execute function private.reject_appointment_during_closed_time();
create function private.set_appointment_service_snapshot() returns trigger language plpgsql as $$begin return new;end$$;
create trigger appointments_set_service_snapshot before insert or update of service_id on appointments for each row execute function private.set_appointment_service_snapshot();`;
(async()=>{
 const {default:EmbeddedPostgres}=await import(require('node:url').pathToFileURL(path.join(runtime,'embedded-postgres/dist/index.js')).href);
 const databaseDir=fs.mkdtempSync(path.join(os.tmpdir(),'salon-calendar-pg-'));
 const server=new EmbeddedPostgres({databaseDir,port:55439,user:'postgres',password:'local-test-only',persistent:true,initdbFlags:['--locale=C','--encoding=UTF8'],postgresFlags:['-h','127.0.0.1'],onLog:()=>{},onError:()=>{}});
 let db,other;
 try{
  await server.initialise();await server.start();
  const config={host:'127.0.0.1',port:55439,user:'postgres',password:'local-test-only',database:'postgres'};
  db=new Client(config);other=new Client(config);await db.connect();await other.connect();
  await db.query(fixture);
  const notifications=fs.readFileSync('supabase/migrations/20260921113000_harden_web_push_appointment_notifications.sql','utf8').match(/create or replace function private\.notify_appointment_assignment\(\)[\s\S]*?\$\$;/i)[0];
  await db.query(notifications);await db.query("create trigger appointments_notify_assignee after insert or update on appointments for each row execute function private.notify_appointment_assignment()");
  await db.query(migration);
  await db.query('grant usage on schema public,auth to service_role;grant all on all tables in schema public to service_role;grant execute on all functions in schema auth to service_role');
  for(const client of [db,other])await client.query("set test.role='service_role'");
  const uuid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),service=uuid(1),employee=uuid(2),manager=uuid(3);
  await db.query("insert into services values($1,'Test',100,25,true)",[service]);await db.query("insert into booking_settings values(true,true,'09:00','20:00')");
  await db.query("insert into profiles values($1,'Personel','personel',true,'employee'),($2,'Yönetici','manager',true,'manager')",[employee,manager]);
  const future=new Date(Date.now()+7*86400000);while(future.getUTCDay()===0)future.setUTCDate(future.getUTCDate()+1);const day=future.toISOString().slice(0,10),at=t=>day+'T'+t+':00+03:00';
  const payload=(n,time)=>({public_token:uuid(n),employee_id:employee,service_id:service,scheduled_at:at(time),duration_minutes:25,client_name:'Test '+n,phone:'90500000'+String(n).padStart(4,'0'),phone_normalized:'90500000'+String(n).padStart(4,'0')});
  const create=(client,p)=>client.query('select create_confirmed_online_booking($1::jsonb) result',[JSON.stringify(p)]);
  await db.query('set role service_role');await other.query('set role service_role');
  const first=(await create(db,payload(10,'10:45'))).rows[0].result;
  assert.equal((await db.query('select scheduled_end-scheduled_at as delta from appointments where id=$1',[first.appointment_id])).rows[0].delta.minutes,25);
  await assert.rejects(create(db,payload(11,'11:00')),/müsait/);
  await create(db,payload(12,'11:15'));
  const manage=(token,operation,revision,action,time)=>db.query('select manage_customer_online_booking($1,$2,$3,$4,$5) result',[uuid(token),uuid(operation),revision,action,time?at(time):null]);
  await assert.rejects(manage(999,20,0,'update','12:00'),/bulunamadı/);
  await manage(10,21,0,'update','12:15');await manage(10,21,0,'update','12:15');
  assert.equal((await db.query("select count(*)::int n from notifications where appointment_id=$1 and recipient_id=$2 and kind='appointment_update'",[first.appointment_id,manager])).rows[0].n,1);
  await assert.rejects(manage(10,22,0,'update','13:00'),/değişti/);
  await db.query('update services set duration_minutes=45 where id=$1',[service]);
  await manage(10,23,1,'update','13:00');
  assert.equal((await db.query('select duration_minutes from appointments where id=$1',[first.appointment_id])).rows[0].duration_minutes,25,'Existing duration survives tariff changes');
  await manage(10,24,2,'cancel');await manage(10,24,2,'cancel');
  assert.equal((await db.query("select count(*)::int n from notifications where appointment_id=$1 and recipient_id=$2 and kind='appointment_cancelled'",[first.appointment_id,manager])).rows[0].n,1);
  assert.equal((await db.query('select status from appointments where id=$1',[first.appointment_id])).rows[0].status,'cancelled');
  await db.query('update services set duration_minutes=25 where id=$1',[service]);await create(db,payload(30,'13:00'));
  // Different connections overlap in time: connection B must wait on A's employee lock.
  await db.query('begin');await create(db,payload(40,'15:00'));
  let settled=false;const attempt=create(other,payload(41,'15:00')).then(()=>({ok:true}),error=>({error})).finally(()=>{settled=true});
  await new Promise(resolve=>setTimeout(resolve,150));assert.equal(settled,false,'Second connection waits for employee transaction');
  await db.query('commit');const loser=await attempt;assert(loser.error,'Only one concurrent online booking succeeds');
  assert.equal((await db.query('select count(*)::int n from appointments where scheduled_at=$1 and status<>\'cancelled\'',[at('15:00')])).rows[0].n,1);
  await db.query('insert into closed_time_slots values($1,$2,$3)',[employee,at('16:00'),at('17:00')]);await assert.rejects(create(db,payload(50,'15:45')),/kapalı/);
  assert.equal((await db.query("select has_function_privilege('anon','manage_customer_online_booking(uuid,uuid,integer,text,timestamptz)','execute') allowed")).rows[0].allowed,false);
  assert.equal((await db.query("select has_function_privilege('authenticated','manage_customer_online_booking(uuid,uuid,integer,text,timestamptz)','execute') allowed")).rows[0].allowed,false);
  const manual=(await db.query("insert into appointments(client_name,service_id,employee_id,scheduled_at,duration_minutes,status,source) values('Manual',$1,$2,$3,25,'confirmed','staff') returning id",[service,employee,at('17:00')])).rows[0].id;
  await db.query('update services set duration_minutes=45 where id=$1',[service]);
  await db.query('update appointments set service_id=$1,scheduled_at=$2 where id=$3',[service,at('17:15'),manual]);
  assert.equal((await db.query('select duration_minutes from appointments where id=$1',[manual])).rows[0].duration_minutes,25);
  const boundary={...payload(60,'18:00'),duration_minutes:45};await create(db,boundary);await create(db,{...payload(61,'18:45'),duration_minutes:45});
  await assert.rejects(db.query("update appointments set staff_overlap_override=true,scheduled_at=$1 where id=$2",[at('18:00'),manual]),/personel/);
  await db.query("set test.role='authenticated'");await db.query("select set_config('test.uid',$1,false)",[manager]);
  await db.query('update appointments set staff_overlap_override=true,scheduled_at=$1 where id=$2',[at('18:00'),manual]);
  assert.equal((await db.query('select staff_overlap_override from appointments where id=$1',[manual])).rows[0].staff_overlap_override,true);
  await db.query("set test.role='service_role';set test.uid=''");
  await db.query("insert into services values($1,'Other',150,45,true)",[uuid(90)]);
  await db.query("set test.role='authenticated'");await db.query("select set_config('test.uid',$1,false)",[manager]);
  await db.query('update appointments set service_id=$1 where id=$2',[uuid(90),manual]);
  assert.equal((await db.query('select duration_minutes from appointments where id=$1',[manual])).rows[0].duration_minutes,45,'Service change adopts new duration');
  const onlineToMove=(await db.query('select appointment_id from online_booking_requests where public_token=$1',[uuid(30)])).rows[0].appointment_id;
  await db.query("set test.role='authenticated'");await db.query("select set_config('test.uid',$1,false)",[manager]);
  await db.query('update appointments set staff_overlap_override=true,scheduled_at=$1 where id=$2',[at('18:00'),onlineToMove]);
  await db.query("set test.role='service_role';set test.uid=''");
  await assert.rejects(manage(30,70,0,'update','18:15'),/müsait/,'Customer cannot use staff overlap exception');
  const duration=(await db.query('select duration_minutes from appointments where id=$1',[first.appointment_id])).rows[0].duration_minutes;assert.equal(duration,25);
  console.log('PASS real PostgreSQL: arbitrary duration, strict overlap, token isolation, revision/replay, manager notification dedup, cancellation freeing, closed slots, TWO-CONNECTION concurrency');
 }finally{if(other)await other.end();if(db)await db.end();await server.stop();console.log('Local fixture retained at',databaseDir)}
})().catch(error=>{console.error(error);process.exitCode=1});
