const assert = require('node:assert/strict');
const fs = require('node:fs');

const migration = fs.readFileSync('supabase/migrations/20260925120000_customer_booking_requests.sql', 'utf8');
const edge = fs.readFileSync('supabase/functions/customer-booking-request/index.ts', 'utf8');
const publicHtml = fs.readFileSync('randevu/index.html', 'utf8');
const publicJs = fs.readFileSync('randevu/booking.js', 'utf8');
const adminJs = fs.readFileSync('booking-requests-admin-2.4.0.js', 'utf8');
const shell = fs.readFileSync('sw.js', 'utf8');
const index = fs.readFileSync('salon-modern.html', 'utf8');
const notificationMigration = fs.readFileSync('supabase/migrations/20260927090000_allow_booking_request_notifications.sql', 'utf8');
const scheduleAdmin = fs.readFileSync('booking-schedule-admin-2.4.1.js', 'utf8');
const scheduleControls = fs.readFileSync('booking-schedule-controls-2.4.3.js', 'utf8');
const phase2 = fs.readFileSync('salon-phase2-1.8.0.js', 'utf8');
const assistant = fs.readFileSync('salon-assistant-2.0.0.js', 'utf8');

assert.doesNotMatch(migration, /create table/i, 'Canlıdaki mevcut talep tablosu tekrar oluşturulmamalı');
assert.match(migration, /alter table public\.online_booking_requests/, 'Mevcut online talep tablosu genişletilmeli');
assert.match(migration, /public_token uuid not null default gen_random_uuid/, 'Tahmin edilemeyen takip kodu olmalı');
assert.match(migration, /alter table public\.online_booking_requests enable row level security/, 'RLS açık kalmalı');
assert.match(migration, /revoke all on table public\.online_booking_requests from anon/, 'Public tablo erişimi kapalı olmalı');
assert.doesNotMatch(migration, /grant insert[^;]+anon/i, 'Anon doğrudan talep tablosuna yazamamalı');

assert.match(edge, /BOOKING_RATE_LIMIT_SALT/, 'Rate limit IP verisi hashlenmeli');
assert.doesNotMatch(edge, /BOOKING_RATE_LIMIT_SALT'\) \|\| SUPABASE_URL/, 'IP hash için tahmin edilebilir fallback kullanılmamalı');
assert.match(edge, /phone_normalized[^\n]+gte\('created_at', since\)/, 'Telefon bazlı rate limit olmalı');
assert.match(edge, /online_booking_requests/, 'Tek talep veri kaynağı kullanılmalı');
assert.match(edge, /request_ip_hash[^\n]+gte\('created_at', since\)/, 'IP bazlı rate limit olmalı');
assert.match(edge, /db\.auth\.getUser\(token\)/, 'Yönetici işlemi JWT ile doğrulanmalı');
assert.match(edge, /eq\('role', 'manager'\)/, 'Yönetici rolü server-side kontrol edilmeli');
assert.match(edge, /action === 'availability'/, 'Public müsaitlik endpointi olmalı');
assert.match(edge, /booking_settings/, 'Varsayılan online çalışma saatleri okunmalı');
assert.match(edge, /booking_schedule_overrides/, 'Tarih bazlı çalışma saati okunmalı');
assert.match(edge, /duration >= 60 \? 60 : 30/, 'Uzun hizmetler saatlik, kısa hizmetler yarım saatlik ilerlemeli');
assert.match(edge, /followsLengthyAppointmentAtHalfHour/, 'Uzun randevudan sonra ara saat yerine sonraki tam saat sunulmalı');
assert.match(edge, /appointmentDuration >= 45 && appointmentEnd === start/, '45 dakika veya uzun işlem ara saatte tam bitiyorsa sonraki tam saat sunulmalı');
assert.doesNotMatch(edge, /appointmentEnd > currentHour/, 'İşlem ara saatten önce biterse ara saat gereksiz engellenmemeli');
assert.match(edge, /minutes <= ONLINE_LAST_START_MINUTES && minutes \+ duration <= schedule\.close/, 'Online başlangıç en geç 19.00 olmalı ve hizmet kapanıştan önce tamamen bitmeli');
assert.match(edge, /ONLINE_LAST_START_MINUTES = 19 \* 60/, 'Online son başlangıç saati 19.00 olarak sabitlenmeli');
assert.match(edge, /db\.from\('closed_time_slots'\)/, 'Online müsaitlik çalışan kapalı saatlerini okumalı');
assert.match(edge, /start < new Date\(item\.ends_at\)\.getTime\(\) && end > new Date\(item\.starts_at\)\.getTime\(\)/, 'Hizmet kapalı aralıkla kısmen çakışsa bile online saat sunulmamalı');
assert.match(edge, /Number\(b.price \|\| 0\) - Number\(a.price \|\| 0\)/, 'Hizmetler sunucuda fiyatı büyükten küçüğe sıralanmalı');
assert.match(edge, /https:\/\/app\.salonmodern\.com\.tr/, 'Özel uygulama alan adı CORS izin listesinde olmalı');
assert.match(edge, /action === 'status'/, 'Güvenli tokenlı durum endpointi olmalı');
assert.match(edge, /create_confirmed_online_booking/, 'Yeni kayıt atomik olarak otomatik onaylanmalı');
assert.match(edge, /automatic confirmation failed/, 'Kayıt hatası sessizce yutulmamalı');
assert.match(notificationMigration, /'booking_request'::text/, 'Bildirim türü veritabanı kısıtında izinli olmalı');

assert.match(publicHtml, /Salon Modern \| Online Randevu/, 'SEO başlığı bulunmalı');
assert.match(publicHtml, /og:title/, 'Open Graph bilgisi bulunmalı');
assert.match(publicHtml, /Randevunuz kaydedildiğinde otomatik onaylanır/, 'Otomatik onay davranışı açık olmalı');
assert.doesNotMatch(publicHtml, /service_role/i, 'Public HTML gizli anahtar içermemeli');
assert.match(publicJs, /action=create/, 'Form Edge Function üzerinden gönderilmeli');
assert.doesNotMatch(publicJs, /\.from\(['"]appointments/, 'Public tarayıcı appointments tablosuna doğrudan yazmamalı');
assert.match(adminJs, /Randevu Talepleri/, 'Yönetici menüsü bulunmalı');
assert.match(adminJs, /typeof currentUser!==['"]undefined['"]/, 'Talep modülü ana uygulamanın kullanıcı durumunu okumalı');
assert.match(adminJs, /SalonBookingRequests\.approve/, 'Onay eylemi bulunmalı');
assert.match(adminJs, /WhatsApp’tan bildir/, 'Manuel WhatsApp eylemi bulunmalı');
assert.match(index, /booking-requests-admin-2\.4\.0\.js/, 'Yönetim uygulaması modülü yüklemeli');
assert.match(shell, /salon-modern-shell-pwa-v88/, 'PWA cache sürümü yükseltilmeli');
assert.match(edge, /onlineBookingEnabled/, 'Katalog online randevu durumunu istemciye bildirmeli');
assert.match(publicJs, /Online randevu geçici olarak kapalı/, 'Kapalı durumda müşteri akışı ilerlememeli');
assert.match(edge, /todaySchedule/, 'Katalog ilk açılışta bugünün çalışma durumunu döndürmeli');
assert.match(publicHtml, /todayClosedNotice/, 'İlk ekranda bugünün kapalı bilgisi için görünür alan bulunmalı');
assert.match(publicJs, /Bugün salon kapalı/, 'Bugün kapalıysa müşteri ilk adımda bilgilendirilmeli');
assert.match(publicJs, /Bugün için randevu saatleri sona erdi/, 'Bugünün çalışma saati bittiyse ilk adımda bilgi verilmeli');
assert.match(edge, /hasRemainingWindow/, 'Katalog bugünün kalan çalışma penceresini bildirmeli');
assert.match(publicJs, /Bu tarihte uygun saat kalmadı/, 'Slotsuz tarih kullanıcıyı saat adımına taşımamalı');
assert.match(publicJs, /if\(!available\)return/, 'Kapalı tarih seçildiğinde saat adımına geçilmemeli');
assert.match(shell, /\.\/randevu\//, 'Public sayfa çevrimdışı shell ayrımında tanınmalı');
assert.match(publicHtml, /\.\.\/salon-modern\.html/, 'Randevu sayfasında personel girişi bulunmalı');
assert.doesNotMatch(publicJs, /dakika<\/small>/, 'Hizmet kartında süre yazmamalı');
assert.doesNotMatch(publicJs, /Çalışan seçimi<\/small>/, 'Çalışan kartında gereksiz alt yazı bulunmamalı');
assert.match(scheduleAdmin, /booking_schedule_overrides/, 'Yönetim paneli tarih override tablosunu kullanmalı');
assert.match(scheduleAdmin, /Varsayılana dön/, 'Seçili tarih varsayılana döndürülebilmeli');
assert.match(scheduleAdmin, /removeMessageUi/, 'Mesaj yönetim arayüzü kaldırılmalı');
assert.match(scheduleAdmin, /appointments\|\|\[\]/, 'Takvim aralığı mevcut randevuları kapsayacak şekilde genişlemeli');
assert.match(scheduleControls, /online_booking_enabled/, 'Online randevu kalıcı açma kapama kontrolü olmalı');
assert.match(scheduleControls, /default_open_time/, 'Genel açılış saati düzenlenebilmeli');
assert.match(scheduleControls, /grid-template-rows/, 'Takvim satırları seçili saat aralığına göre ekrana sığmalı');
assert.match(scheduleControls, /amount\.readOnly=false;amount\.disabled=false/, 'Randevu ücreti elle değiştirilebilir olmalı');
assert.match(scheduleControls, /Hizmet fiyatı otomatik gelir; bu randevu için değiştirebilirsiniz\./, 'Manuel randevu ücreti davranışı kullanıcıya açıklanmalı');
assert.match(edge, /neq\('username', 'salon\.modern'\)/, 'Yalnız yönetim hesabı çalışan seçeneklerine girmemeli');
assert.match(edge, /getUTCDay\(\) === 0/, 'Özel ayar yoksa pazar günü kapalı olmalı');
assert.match(scheduleAdmin, /getDay\(\)===0/, 'Yönetim takvimi de pazar gününü varsayılan kapalı saymalı');
assert.match(scheduleAdmin, /half=time\.slice\(3\)===['"]00['"]\|\|time\.slice\(3\)===['"]30['"]/, 'Yönetim takviminde saat ve yarım saat başlangıçları seçilebilmeli');
assert.match(scheduleAdmin, /for\(var minute=display\.start;minute<display\.end;minute\+=15\)/, 'Kapanış saati yalnız bitiş sınırı olmalı');
assert.match(scheduleAdmin, /window\.remoteClosedSlots\|\|\[\]/, 'Kapalı saatler son takvim rendererında görünür blok olarak çizilmeli');
assert.match(scheduleAdmin, /duration-closed-event/, 'Kapalı saat bloğu ayrı görünüm sınıfı kullanmalı');
assert.match(scheduleAdmin, /openClosedSlotModal/, 'Kapalı saat bloğu düzenleme ekranını açmalı');
assert.match(adminJs, /approvedWhatsappUrl/, 'Online onay ve manuel bildirim ortak WhatsApp üreticisini kullanmalı');
assert.match(adminJs, /window\.whatsappAppointmentUrl/, 'Online onay mevcut appointment_confirmation şablon akışını kullanmalı');
assert.doesNotMatch(adminJs, /randevu talebiniz onaylandı/, 'Ayrı hardcoded onay mesajı tutulmamalı');
assert.match(adminJs, /if\(url\)window\.location\.href=url/, 'WhatsApp yalnız geçerli onay URLsi üretildiğinde açılmalı');
assert.match(scheduleControls, /amount\.readOnly=false/, 'Randevu ücret alanı elle düzenlenebilir olmalı');
assert.match(scheduleControls, /amount\.disabled=false/, 'Randevu ücret alanı etkin kalmalı');
assert.match(index, /nextHour=Math\.min\(1440,\(Math\.floor\(startMinute\/60\)\+1\)\*60\)/, 'Kapalı saat seçimi bir sonraki tam saate kadar tüm aralığı kapatmalı');
assert.match(index, /closedSlotStart['"]\)\.onchange/, 'Kapalı saat başlangıcı değişince bitiş önerisi birlikte güncellenmeli');
assert.match(adminJs, /booking-schedule-admin-2\.4\.1\.js\?v=81/, 'Takvim düzeltmesi eski tarayıcı önbelleğinden ayrılmalı');
assert.match(scheduleControls, /appointment-editing/, 'Randevu güncelleme görünümü yeni kayıttan ayrılmalı');
assert.match(scheduleControls, /#appointmentModal\.appointment-editing #appointmentRecurrence\{display:none!important\}/, 'Güncellemede kullanılamayan tekrar alanı gizlenmeli');
assert.match(scheduleControls, /max-height:calc\(100svh/, 'Randevu modalı ekran yüksekliğiyle sınırlandırılmalı');
assert.match(scheduleAdmin, /end=Math\.ceil\(end\/60\)\*60/, 'Yarım saatte biten görünüm son tam saate tamamlanmalı');
assert.match(scheduleControls, /endLabel\.textContent=''/, 'Teknik bitiş sınırı yeni bir saat dilimi gibi gösterilmemeli');
assert.match(scheduleControls, /repeat\('\+slots\+',minmax\(8px,1fr\)\) 0px/, 'Teknik bitiş satırı takvim altında boş alan bırakmamalı');
assert.match(index, /appointmentStart=time\.slice\(3\)===['"]00['"]\|\|time\.slice\(3\)===['"]30['"]/, 'Yönetim takviminde saat ve yarım saat başlangıçları aktif olmalı');
assert.match(index, /480\+\(index\*30\)/, 'Randevu formu yalnız 30 dakikalık başlangıçlar üretmeli');
assert.match(scheduleAdmin, /step="1800"/, 'Tarih özelindeki çalışma saatleri yalnız tam veya yarım saat seçtirmeli');
assert.match(scheduleControls, /step="1800"/, 'Genel çalışma saatleri yalnız tam veya yarım saat seçtirmeli');
assert.doesNotMatch(index, /<option value="19:45"/, '19.45 randevu başlangıcı sunulmamalı');
assert.match(phase2, /profile\.active&&profile\.username!==['"]salon\.modern['"]/, 'Yalnız yönetici hesabı günlük çalışan özetine katılmamalı');
assert.match(assistant, /p\.active&&p\.username!==['"]salon\.modern['"]/, 'Yalnız yönetici hesabı asistan çalışan sonuçlarına katılmamalı');
assert.match(scheduleControls, /installAdminProfileFilters/, 'Önbellekte kalan eski özet kodu için yönetici profili çalışma anında da filtrelenmeli');

console.log('customer booking request tests: PASS');
