const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(path.join(process.argv[2],'playwright'));
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:430,height:850},hasTouch:true,isMobile:true});const fixtureDate=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Istanbul'}).format(new Date(Date.now()+3*86400000));let revision=0,status='approved',scheduledAt=fixtureDate+'T10:00:00+03:00',updates=0,cancels=0;
 await page.route('https://fixture.test/**',route=>{const file=new URL(route.request().url()).pathname.endsWith('manage.js')?'randevu/durum/manage.js':new URL(route.request().url()).pathname.endsWith('booking.css')?'randevu/booking.css':'randevu/durum/index.html';return route.fulfill({status:200,contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html',body:fs.readFileSync(file,'utf8')})});
 await page.route('https://oxuwwjsakhcqimjsfris.supabase.co/**',async route=>{const req=route.request(),action=new URL(req.url()).searchParams.get('action');let data;if(action==='status')data={status,revision,appointment:{customer:'Test Customer',service:'Read-only service',employee:'Read-only employee',scheduledAt,durationMinutes:25,amount:100,canManage:status==='approved'}};else if(action==='customer-availability')data={slots:[{time:'10:30',employeeIds:['e1']}]};else{const body=req.postDataJSON();assert.equal(body.revision,revision);assert(!body.appointmentId&&!body.serviceId&&!body.employeeId);await new Promise(resolve=>setTimeout(resolve,80));if(action==='customer-update'){updates++;scheduledAt=body.date+'T'+body.time+':00+03:00'}else{cancels++;status='cancelled'}revision++;data={status,revision}}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)})});
 await page.goto('https://fixture.test/randevu/durum/?token=00000000-0000-4000-8000-000000000001');await page.locator('#manage').waitFor({state:'visible'});assert.match(await page.locator('#result').innerText(),/Read-only service/);await page.locator('#time').selectOption('10:30');await page.locator('#update').click();await page.waitForFunction(()=>document.getElementById('message').textContent==='Randevunuz güncellendi.');assert.equal(updates,1);
 await page.locator('#cancel').click();assert.equal(cancels,0);await page.locator('#keep').click();assert.equal(cancels,0);await page.locator('#cancel').click();await page.locator('#confirmCancel').click();await page.waitForFunction(()=>document.getElementById('message').textContent==='Randevunuz iptal edildi.');assert.equal(cancels,1);assert.equal(await page.locator('#manage').isVisible(),false);
 console.log('PASS customer browser: token link, readonly service/employee, availability, date/time update, cancellation confirmation, cancel/no mutation, successful soft cancellation and one request');
}finally{await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
