const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('salon-finance-2.3.0.js','utf8');
const elements={finance230PeriodSummary:{innerHTML:''},finance230PeriodRecords:{innerHTML:''}};
const ctx=vm.createContext({window:{},document:{getElementById:id=>elements[id]},finance230PeriodFilter:null,finance230PeriodRequest:0,finance230PeriodExpenses:[],financeState:{expenses:[]},today:()=> '2026-10-01',esc:v=>String(v).replace(/</g,'&lt;'),money:String,errText:e=>e.message,manager:()=>true});
vm.runInContext(source.slice(source.indexOf('function finance230MonthBounds('),source.indexOf('async function renderFinance230Summary(')),ctx);
assert.equal(ctx.finance230MonthBounds('2024-02').end,'2024-02-29');
assert.equal(ctx.finance230MonthBounds('2026-12').end,'2026-12-31');
assert.equal(ctx.finance230MonthBounds('2027-02').end,'2027-02-28');
assert.match(ctx.finance230PeriodHtml(),/2026-10/);
assert.match(source, /holder\.innerHTML='<div[^\n]+Günlük kasa ve kapanış[^\n]+\+expenseFormHtml\(\)\+finance230PeriodHtml\(\)/, 'Daily cash, expense form and period report must appear in that order');
assert.deepEqual(JSON.parse(JSON.stringify(ctx.finance230PeriodDates())),{start:'2026-10-01',end:'2026-10-31'});
ctx.finance230PeriodFilter={mode:'range',start:'2026-10-02',end:'2026-10-01'};assert.throws(()=>ctx.finance230PeriodDates(),/kontrol/);
ctx.finance230PeriodFilter={mode:'range',start:'2026-02-30',end:'2026-03-01'};assert.throws(()=>ctx.finance230PeriodDates(),/kontrol/);
ctx.finance230PeriodFilter={mode:'range',start:'2026-10-01',end:'2026-10-01'};assert.equal(ctx.finance230PeriodDates().end,'2026-10-01');
let queries=[],rpcCalls=[],oldRpc,oldRows;
const summary={start_date:'2026-10-01',end_date:'2026-10-31',gross_turnover:1000,distributable_revenue:800,distributable_amount:500,daily_expenses:50,main_expenses:80,all_expenses:130,reserve_contribution:100,fund_posted_contribution:60,fund_opening_balance:200,fund_closing_balance:180,day_count:31,closed_days:1};
ctx.salonDb={rpc(name,args){rpcCalls.push({name,args});if(args.p_start==='2026-09-01')return new Promise(resolve=>oldRpc=resolve);return Promise.resolve({data:summary})},from(table){assert.equal(table,'business_expenses');let start,end;return {select(){return this},gte(field,v){assert.equal(field,'expense_date');start=v;return this},lte(field,v){assert.equal(field,'expense_date');end=v;return this},order(){return this},range(offset,last){queries.push({start,end,offset,last});if(start==='2026-09-01')return new Promise(resolve=>oldRows=resolve);return Promise.resolve({data:offset===0?Array.from({length:500},(_,i)=>({id:String(i),expense_date:i<250?'2026-10-02':'2026-10-01',category:i===0?'<unsafe>':'Gider',account_scope:i===1?'reserve':'daily',amount:1})):[{id:'last',expense_date:'2026-10-01',category:'Last',amount:1}]})}}}};
(async()=>{
 ctx.finance230PeriodFilter={mode:'month',month:'2026-10'};
 await ctx.renderFinance230Period();assert.equal(ctx.finance230PeriodExpenses.length,501);assert.equal(queries.length,2);
 assert.equal(rpcCalls[0].name,'calculate_cash_period_summary');assert.equal(rpcCalls[0].args.p_end,'2026-10-31');
 assert.match(elements.finance230PeriodSummary.innerHTML,/Seçilen dönemde kalan/);assert.match(elements.finance230PeriodSummary.innerHTML,/Fona işlenen katkı/);
 assert.match(elements.finance230PeriodRecords.innerHTML,/2026-10-02/);assert.match(elements.finance230PeriodRecords.innerHTML,/2026-10-01/);assert.match(elements.finance230PeriodRecords.innerHTML,/&lt;unsafe>/);
 assert.equal((elements.finance230PeriodRecords.innerHTML.match(/<h4>/g)||[]).length,2);
 let edited;ctx.editFinance230Expense=id=>edited=id;ctx.editFinance230PeriodExpense('last');assert.equal(edited,'last');assert.equal(ctx.financeState.expenses[0].id,'last');assert.equal(ctx.finance230PeriodFilter.month,'2026-10');
 ctx.finance230PeriodFilter={mode:'month',month:'2026-09'};const old=ctx.renderFinance230Period();
 ctx.finance230PeriodFilter={mode:'month',month:'2026-10'};await ctx.renderFinance230Period();oldRpc({data:{...summary,distributable_amount:99999}});oldRows({data:[{id:'stale'}]});await old;
 assert.doesNotMatch(elements.finance230PeriodSummary.innerHTML,/99999/);assert.equal(ctx.finance230PeriodExpenses.length,501);
 ctx.salonDb.rpc=()=>Promise.resolve({error:{message:'TEST_RPC_ERROR'}});await ctx.renderFinance230Period();assert.match(elements.finance230PeriodSummary.innerHTML,/TEST_RPC_ERROR/);assert.equal(elements.finance230PeriodRecords.innerHTML,'');
 assert.match(ctx.finance230PeriodRecordsHtml([]),/Bu dönemde gider kaydı yok/);
 ctx.manager=()=>false;const calls=rpcCalls.length;await ctx.renderFinance230Period();assert.equal(rpcCalls.length,calls);
 assert.doesNotMatch(source.slice(source.indexOf('function finance230MonthBounds('),source.indexOf('async function renderFinance230Summary(')),/close_daily_cash/);
 console.log('PASS period filters, leap/year boundaries, 501 expenses, grouped dates, editing, stale responses, errors and manager guard');
})().catch(e=>{console.error(e);process.exitCode=1});
