const fs=require('node:fs'),assert=require('node:assert/strict');
const sql=fs.readFileSync('supabase/migrations/20261008152000_manual_whatsapp_thank_you_queue.sql','utf8');
const ui=fs.readFileSync('manual-whatsapp-thank-you-2.4.6.js','utf8');
const html=fs.readFileSync('salon-modern.html','utf8');
const push=fs.readFileSync('salon-web-push.js','utf8');
const migration=fs.readFileSync('supabase/migrations/20261008190000_manual_thank_you_push.sql','utf8');
assert.match(sql,/a\.status='completed'/);
assert.match(sql,/whatsapp_marketing_opt_in/);
assert.match(sql,/whatsapp_marketing_opt_out_at is null/);
assert.match(sql,/appointment_thank_you:'\|\|a\.id::text/);
assert.match(sql,/status,attempt_count,sent_at,status_at,metadata/);
assert.match(sql,/manual_wa_me/);
assert.match(sql,/not exists[\s\S]*whatsapp_message_logs/);
assert.match(ui,/https:\/\/wa\.me\//);
assert.match(ui,/encodeURIComponent\(messageFor\(row\)\)/);
assert.match(ui,/WhatsApp\\'tan Teşekkür Et/);
assert.match(ui,/Gönderildi Olarak İşaretle/);
assert.match(ui,/whatsapp_marketing_opt_in_at:now/);
assert.match(html,/manual-whatsapp-thank-you-2\.4\.6\.js\?v=119/);
assert.match(migration,/notifications_one_thank_you_per_appointment/);
assert.match(migration,/private\.enqueue_due_manual_thank_you_pushes/);
assert.match(migration,/a\.completed_at\+make_interval\(mins=>s\.whatsapp_thank_you_delay_minutes\)/);
assert.match(migration,/when a\.created_by is not null then a\.created_by/);
assert.match(push,/data\.kind==='appointment_thank_you'/);
assert.match(ui,/openManualThankYouFromNotification/);
assert.match(ui,/renderSavedTemplate\('appointment_thank_you'/);
console.log('PASS manual WhatsApp thank-you queue, consent, wa.me draft and shared dedupe');
