const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
let handler;
const NativeDate=Date;
let nowMs=new NativeDate('2026-10-04T12:00:00+03:00').getTime();
class TestDate extends NativeDate{constructor(...args){super(...(args.length?args:[nowMs]))}static now(){return nowMs}}
const hourServiceIds=['2638b0ff-a6e0-412c-b212-0f4d238d9be1','620dbf23-22f9-4362-85a4-eed7c377e9be','0cdc2d09-b75e-4545-ba73-1c01665400c7','65f7f4ae-77ff-4409-b10a-5607a05aceee'];
let services=Array.from({length:6},(_,i)=>({id:i<4?hourServiceIds[i]:'s'+i,name:'Hizmet '+i,price:600-i*50,duration_minutes:[60,45,90,30,30,15][i]})).reverse();
let overrides=null,appointments=[],closures=[],rpcCalls=[],existing=null,rpcError=null,bookingAllowed=true;
const db={rpc(name,args){if(name==='can_create_online_booking')return Promise.resolve({data:bookingAllowed,error:null});rpcCalls.push({name,args});return Promise.resolve({data:{id:'12345678-0000-4000-8000-000000000001',public_token:args.p_booking?.public_token},error:rpcError})},from(table){let single=false;const filters={};const query={select(){return this},returns(){return this},eq(key,value){filters[key]=value;return this},neq(){return this},in(){return this},gte(){return this},lte(){return this},lt(){return this},gt(){return this},order(){return this},maybeSingle(){single=true;return this},then(resolve,reject){let data=table==='services'?(single?services.find(s=>s.id===filters.id):services):table==='profiles'?(single?{id:'e1'}:[{id:'e1'}]):table==='booking_settings'?{online_booking_enabled:true,default_open_time:'09:00',default_close_time:'20:00'}:table==='booking_schedule_overrides'?overrides:table==='appointments'?appointments:table==='online_booking_requests'?existing:closures;return Promise.resolve({data,error:null,count:0}).then(resolve,reject)}};return query}};
let source=fs.readFileSync('supabase/functions/customer-booking-request/index.ts','utf8').replace(/^import[^\n]+\n/,'');
const ctx=vm.createContext({createClient:()=>db,Deno:{env:{get:()=>''},serve:fn=>handler=fn},Request,Response,URL,Intl,Date:TestDate,crypto,TextEncoder,console});
vm.runInContext(stripTypeScriptTypes(source,{mode:'transform'}),ctx);
async function slots(service){const url=new URL('https://test/?action=availability&date=2026-10-05&service='+service);return (await handler(new Request(url))).json()}
(async()=>{
 const ranked=await vm.runInContext('onlineServices()',ctx);
 assert.deepEqual(Array.from(ranked,x=>x.id),[...hourServiceIds,'s4','s5']);
 assert.deepEqual(Array.from(ranked,x=>x.duration_minutes),[60,45,90,30,30,15],'Service master durations stay unchanged');
 assert.deepEqual(Array.from(ranked,x=>x.online_duration_minutes),[60,60,60,60,30,30]);
 for(const id of hourServiceIds){const hourData=await slots(id);assert.equal(hourData.durationMinutes,60)}
 let data=await slots(hourServiceIds[0]);assert.equal(data.durationMinutes,60);assert(!data.slots.some(x=>x.time==='09:15'));assert(data.slots.some(x=>x.time==='09:30'));assert(data.slots.some(x=>x.time==='19:00'));assert(!data.slots.some(x=>x.time==='19:30'));
 data=await slots('s4');assert.equal(data.durationMinutes,30);assert(data.slots.some(x=>x.time==='09:30'));assert(!data.slots.some(x=>x.time==='19:30'));
 overrides={open_time:'10:00',close_time:'11:00',is_closed:false};data=await slots(hourServiceIds[0]);assert.deepEqual(data.slots.map(x=>x.time),['10:00']);
 closures=[{employee_id:'e1',starts_at:'2026-10-05T10:30:00+03:00',ends_at:'2026-10-05T11:15:00+03:00'}];data=await slots(hourServiceIds[0]);assert.equal(data.slots.length,0);
 overrides={is_closed:true};data=await slots('s4');assert.equal(data.slots.length,0);
 overrides=null;closures=[];
 const payload={customerName:'Test Person',customerPhone:'05000000001',serviceId:hourServiceIds[0],employeeId:'e1',date:'2026-10-05',time:'10:00',submissionToken:'00000000-0000-4000-8000-000000000001'};
 const create=p=>handler(new Request('https://test/?action=create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}));
 let response=await create(payload);assert.equal(response.status,201);assert.equal((await response.json()).status,'approved');assert.equal(rpcCalls.length,1);assert.equal(rpcCalls[0].args.p_booking.duration_minutes,60);
 response=await create({...payload,serviceId:'s4',time:'10:30'});assert.equal(response.status,201);assert.equal(rpcCalls[1].args.p_booking.duration_minutes,30);
 bookingAllowed=false;response=await create({...payload,submissionToken:'00000000-0000-4000-8000-000000000009'});assert.equal(response.status,403);assert.equal((await response.json()).error,'Online randevu oluşturma işleminiz için lütfen Salon Modern ile iletişime geçiniz.');assert.equal(rpcCalls.length,2,'No-show restriction must stop before appointment creation');bookingAllowed=true;
 existing={id:'12345678-0000-4000-8000-000000000001',public_token:payload.submissionToken,status:'approved',phone_normalized:'905000000001',service_id:hourServiceIds[0],employee_id:'e1',scheduled_at:'2026-10-05T10:00:00+03:00'};
 response=await create(payload);assert.equal(response.status,200);assert.equal(rpcCalls.length,2,'Retry must not create another appointment');existing=null;
 rpcError={message:'conflict'};response=await create(payload);assert.equal(response.status,409);assert(!(await response.json()).status);rpcError=null;
 services.find(s=>s.id===hourServiceIds[0]).price=1;assert.equal((await vm.runInContext('onlineServices()',ctx)).find(s=>s.id===hourServiceIds[0]).online_duration_minutes,60,'Approved service remains 60 minutes if display order changes');
 data=await slots(hourServiceIds[1]);assert.equal(data.durationMinutes,60);assert(data.slots.some(x=>x.time==='09:30'));
 data=await slots(hourServiceIds[2]);assert.equal(data.durationMinutes,60);assert(!data.slots.some(x=>x.time==='09:45'));assert(data.slots.some(x=>x.time==='10:00'));assert(data.slots.some(x=>x.time==='19:00'));
 const sql=fs.readFileSync('supabase/migrations/20261001063305_online_booking_auto_confirm.sql','utf8');
 assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/security invoker/);assert.match(sql,/from public,anon,authenticated/);assert.match(sql,/'approved',appointment,now\(\)/);assert.doesNotMatch(sql,/update public\.online_booking_requests/);
 const js=fs.readFileSync('randevu/booking.js','utf8');assert.match(js,/if\(button.disabled\)return/);assert.match(js,/submissionToken/);assert.match(js,/data.status!=='approved'/);
 services.find(s=>s.id===hourServiceIds[0]).duration_minutes=25;
 appointments=[{id:'other',employee_id:'e1',scheduled_at:'2026-10-05T10:00:00+03:00',duration_minutes:45}];
 data=await slots(hourServiceIds[0]);assert(data.slots.some(x=>x.time==='11:00'));assert(!data.slots.some(x=>x.time==='10:30'));
 appointments=[{id:'overnight',employee_id:'e1',scheduled_at:'2026-10-04T23:00:00+03:00',duration_minutes:645}];
 data=await slots(hourServiceIds[0]);assert(!data.slots.some(x=>x.time==='09:30'));assert(data.slots.some(x=>x.time==='10:00'));
 existing={status:'approved',customer_revision:0,scheduled_at:'2026-10-05T10:00:00+03:00',appointment:{id:'own',client_name:'Secret Customer',service_name:'Saved service',service_id:hourServiceIds[0],employee_id:'e1',duration_minutes:25,scheduled_at:'2026-10-05T10:00:00+03:00',amount:100,status:'confirmed',employee:{full_name:'Employee'}}};
 appointments=[{id:'own',employee_id:'e1',scheduled_at:existing.scheduled_at,duration_minutes:25}];
 response=await handler(new Request('https://test/?action=customer-availability&token='+payload.submissionToken+'&date=2026-10-05&employee=foreign&service=foreign'));data=await response.json();assert.equal(response.status,200);assert(data.slots.some(x=>x.time==='10:00'),'Token availability excludes only its own appointment');
  response=await handler(new Request('https://test/?action=status&token='+payload.submissionToken));data=await response.json();assert.equal(data.appointment.customer,'Secret Customer');assert.equal(data.appointment.durationMinutes,25);assert.equal(data.revision,0);
  response=await handler(new Request('https://test/?action=customer-update',{method:'POST',body:JSON.stringify({token:payload.submissionToken,appointmentId:'foreign'})}));assert.equal(response.status,400,'Foreign appointment IDs cannot be accepted');
  existing.appointment.scheduled_at=new NativeDate(nowMs+2*60*60*1000).toISOString();existing.scheduled_at=existing.appointment.scheduled_at;
  response=await handler(new Request('https://test/?action=status&token='+payload.submissionToken));data=await response.json();assert.equal(data.appointment.canManage,true,'Exactly two hours must be manageable');assert.equal(data.managementMessage,null);
  response=await handler(new Request('https://test/?action=customer-cancel',{method:'POST',body:JSON.stringify({token:payload.submissionToken,operation:'00000000-0000-4000-8000-000000000020',revision:0})}));assert.equal(response.status,200,'Backend must allow cancellation at exactly two hours');
  existing.appointment.scheduled_at=new NativeDate(nowMs+119*60*1000).toISOString();existing.scheduled_at=existing.appointment.scheduled_at;
  response=await handler(new Request('https://test/?action=customer-availability&token='+payload.submissionToken+'&date=2026-10-05'));assert.equal(response.status,409,'Backend must reject changes with less than two hours left');
  response=await handler(new Request('https://test/?action=customer-cancel',{method:'POST',body:JSON.stringify({token:payload.submissionToken,operation:'00000000-0000-4000-8000-000000000021',revision:0})}));data=await response.json();assert.equal(response.status,409);assert.match(data.error,/2 saatten az/);
  existing.appointment.scheduled_at=new NativeDate(nowMs+121*60*1000).toISOString();existing.scheduled_at=existing.appointment.scheduled_at;
  response=await handler(new Request('https://test/?action=status&token='+payload.submissionToken));data=await response.json();assert.equal(data.appointment.canManage,true,'More than two hours must remain manageable');
  existing=null;response=await handler(new Request('https://test/?action=status&token='+payload.submissionToken));assert.equal(response.status,404);
 console.log('PASS online service policy, half-hour grid, no-show denial, strict overlap and token isolation');
})().catch(err=>{console.error(err);process.exitCode=1});
