const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const posts=[],filters=[],delegated=[],warnings=[],timers=[],storage=new Map();
let notes=[],queryError=null,onQuery=null;
const starts=new Date(Date.now()+45*60*1000).toISOString();
const valid={id:'n1',recipient_id:'u1',appointment_id:'a1',kind:'appointment_reminder',reminder_for:starts,created_at:new Date().toISOString(),title:'Randevu Hatırlatması',body:'Fixture',appointment:{id:'a1',scheduled_at:starts,status:'confirmed'}};
const window={addEventListener(){},deliverAssignmentNotification:item=>delegated.push(item),getSalonAuthState:()=> 'AUTHENTICATED'};
const context={window,currentUser:{id:'u1'},document:{hidden:false,addEventListener(){}},Notification:{permission:'granted'},navigator:{serviceWorker:{ready:Promise.resolve({active:{postMessage:data=>posts.push(data)}}),addEventListener(){}}},salonDb:{from(table){assert.equal(table,'notifications');const q={select(){return q},eq(k,v){filters.push([k,v]);return q},gte(){return q},order(){return q},limit(){return q},then(resolve,reject){if(onQuery)onQuery();return Promise.resolve({data:notes,error:queryError}).then(resolve,reject)}};return q},auth:{}},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},location:{},setInterval:(f,ms)=>timers.push({f,ms}),setTimeout(){},Date,Intl,URL,URLSearchParams,console:{warn:(...a)=>warnings.push(a)}};
context.caches={open:async()=>({match:async url=>url.endsWith('/n1')?new Response(JSON.stringify({notificationId:'n1',pushReceivedAt:'fixture-received',shownAt:'fixture-shown'})):undefined})};
context.navigator.serviceWorker.ready=Promise.resolve({scope:'https://fixture.test/',active:{postMessage:data=>posts.push(data)}});
window.PushManager=function(){};window.Notification=context.Notification;
vm.createContext(context);vm.runInContext(fs.readFileSync('salon-web-push.js','utf8'),context);
(async()=>{
  notes=[valid];await window.deliverAssignmentNotification(valid);
  assert.equal(posts.length,1,'The previously ignored realtime reminder must reach the worker');
  assert(filters.some(([k,v])=>k==='recipient_id'&&v==='u1'));assert(filters.some(([k,v])=>k==='kind'&&v==='appointment_reminder'));
  assert.equal(posts[0].data.kind,'appointment_reminder');assert.equal(posts[0].data.tag,'salon-n1');assert.equal(posts[0].data.reminderFor,starts);
  window.deliverAssignmentNotification({kind:'appointment',recipient_id:'u1'});assert.equal(delegated.length,1,'Existing assignment handler is unchanged');
  posts.length=0;
  notes=[{...valid,recipient_id:'u2'},{...valid,appointment:{...valid.appointment,status:'cancelled'}},{...valid,appointment:{...valid.appointment,scheduled_at:new Date(Date.now()+90*60000).toISOString()}},{...valid,reminder_for:new Date(Date.now()-60000).toISOString(),appointment:{...valid.appointment,scheduled_at:new Date(Date.now()-60000).toISOString()}},{...valid,appointment:null}];
  await window.SalonWebPush.catchUpReminders();assert.equal(posts.length,0,'Other users, cancellations, moved/expired appointments and inaccessible RLS rows must not display');
  notes=[valid];context.document.hidden=true;await window.SalonWebPush.catchUpReminders();assert.equal(posts.length,0,'Foreground fallback must not become a background page timer');context.document.hidden=false;
  context.Notification.permission='denied';await window.SalonWebPush.catchUpReminders();assert.equal(posts.length,0);context.Notification.permission='granted';
  onQuery=()=>{context.currentUser={id:'u2'}};await window.SalonWebPush.catchUpReminders();assert.equal(posts.length,0,'Account switch during query must discard former account results');onQuery=null;context.currentUser={id:'u1'};
  queryError={message:'Fixture offline'};await window.SalonWebPush.catchUpReminders();assert.equal(posts.length,0);assert(warnings.length);queryError=null;
  await window.SalonWebPush.catchUpReminders();assert.equal(posts.length,1,'Transient query error remains retryable');
  assert(timers.some(x=>x.ms===60000),'Visible sessions must recover a missed realtime event within one minute');
  notes=[valid,{...valid,id:'missing-device-receipt'}];const receipts=await window.SalonWebPush.reminderDiagnostics();
  assert.equal(receipts[0].shownAt,'fixture-shown');assert.equal(receipts[1].status,'no-device-receipt');assert(!JSON.stringify(receipts).includes(valid.body),'Diagnostics expose only receipt metadata');
  console.log('PASS reminder foreground recovery: realtime, own-account query, cancellation/time validation, account switch, permission, offline retry and periodic catch-up');
})().catch(e=>{console.error(e);process.exitCode=1});
