const assert=require('node:assert/strict'),fs=require('node:fs');
const html=fs.readFileSync('salon-modern.html','utf8');
const saves=[...html.matchAll(/saveAppointment=async function\(event\)\{/g)];
const finalSave=html.slice(saves[saves.length-2].index,saves[saves.length-1].index);
assert.match(finalSave,/if\(scheduleChanged\)/);
assert.match(finalSave,/showAppToast\('Bu saat dolu'/);
assert.doesNotMatch(finalSave,/Yine de|salonConfirmedAppointmentSignature|staff_overlap_override/);
assert.match(finalSave,/closedSlotFor\(dates\[i\],time,duration,employee.id\)/);
const drag=fs.readFileSync('appointment-form-actions-2.3.30.js','utf8');
assert.doesNotMatch(drag,/Yine de|staff_overlap_override/);
assert.match(drag,/appointmentActionConfirm\('Taşı'/);
assert.equal((drag.match(/showAppToast\('Bu saat dolu'/g)||[]).length,2);
const migration=fs.readFileSync('supabase/migrations/20261002085950_enforce_staff_appointment_conflicts.sql','utf8');
assert.match(migration,/pg_advisory_xact_lock/);assert.match(migration,/security invoker/);
assert.doesNotMatch(migration,/disable row level security|update public.appointments|delete from|if new.staff_overlap_override/i);
console.log('PASS strict create/edit/drag guards, unchanged-schedule edits, locking and preserved records/RLS');
