const assert=require('node:assert/strict'),fs=require('node:fs');
const html=fs.readFileSync('salon-modern.html','utf8');
const picker=html.match(/refreshAppointmentTimeAvailability=function\(\)\{[^\r\n]+/)[0];
assert.match(picker,/closedSlotFor\(date,option.value,appointmentFormDuration\(\),employee.id\)/);
assert.doesNotMatch(picker,/appointmentConflictFor/,'Staff occupied times remain selectable with confirmation');
const saves=[...html.matchAll(/saveAppointment=async function\(event\)\{/g)];
const finalSave=html.slice(saves[saves.length-2].index,saves[saves.length-1].index);
assert.match(finalSave,/appointmentActionConfirm\(originalId\?'Yine de güncelle':'Yine de ekle'/,'Both create and edit require explicit overlap confirmation');
assert.match(finalSave,/closedSlotFor\(dates\[i\],time,duration,employee.id\)/,'Closed-slot rule uses real duration');
const migration=fs.readFileSync('supabase/migrations/20261001143351_allow_staff_appointment_overlap.sql','utf8');
assert.match(migration,/new.source='online' and new.status<>'cancelled'/);
assert.match(migration,/pg_advisory_xact_lock/);
assert.match(migration,/security invoker/);
assert.doesNotMatch(migration,/disable row level security|update public.appointments|delete from/i);
console.log('PASS staff creation picker/save, closed slots, online-only trigger, locking and unchanged records/RLS');
