const fs=require('node:fs'),assert=require('node:assert/strict');
const migration=fs.readFileSync('supabase/migrations/20261008123000_whatsapp_links_and_thank_you.sql','utf8');
const edge=fs.readFileSync('supabase/functions/whatsapp-outbound-dispatch/index.ts','utf8');
const shared=fs.readFileSync('supabase/functions/_shared/meta-whatsapp.mjs','utf8');
const ui=fs.readFileSync('whatsapp-messages-2.4.5.js','utf8');
const html=fs.readFileSync('salon-modern.html','utf8');
assert.match(migration,/appointment_reminder_minutes set default 60/);
assert.match(migration,/set appointment_reminder_minutes=60/);
assert.match(migration,/whatsapp_thank_you_enabled boolean not null default false/);
assert.match(migration,/whatsapp_marketing_opt_in and c\.whatsapp_marketing_opt_in_at is not null/);
assert.match(migration,/c\.whatsapp_marketing_opt_out_at is null/);
assert.match(migration,/a\.status='completed' and a\.completed_at is not null/);
assert.match(migration,/on conflict\(idempotency_key\) do nothing/);
assert.match(migration,/salon_modern_tesekkur_v1/);
assert.match(edge,/whatsapp_enqueue_due_thank_yous/);
assert.match(edge,/thank_you_not_eligible/);
assert.match(shared,/appointment_thank_you/);
assert.match(shared,/\{google_haritalar_url\}/);
assert.match(ui,/Google Haritalar yol tarifi URL/);
assert.match(ui,/Pazarlama izni zorunludur/);
assert.match(ui,/Meta tarafından onaylanmadan otomatik gönderim açılamaz/);
assert.match(html,/whatsapp-messages-2\.4\.5\.js\?v=113/);
console.log('PASS WhatsApp links, 60-minute reminder and opt-in thank-you safeguards');
