(function(){
'use strict';
var API='https://oxuwwjsakhcqimjsfris.supabase.co/functions/v1/customer-booking-request',step=1,catalogue={services:[],employees:[]},state={serviceId:'',employeeId:'',date:'',time:''};
var q=function(id){return document.getElementById(id)},escapeHtml=function(value){return String(value||'').replace(/[&<>"']/g,function(char){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]})};
function error(message){q('formError').textContent=message||''}
async function json(url,options){var response=await fetch(url,options),data=await response.json().catch(function(){return {}});if(!response.ok)throw new Error(data.error||'Sunucuya ulaşılamadı.');return data}
function service(){return catalogue.services.find(function(item){return item.id===state.serviceId})}
function employee(){return catalogue.employees.find(function(item){return item.id===state.employeeId})}
function choose(container,key,value){state[key]=value;Array.from(q(container).querySelectorAll('button')).forEach(function(button){button.classList.toggle('selected',button.dataset.value===value)});error('')}
function renderCatalogue(){q('services').innerHTML=catalogue.services.map(function(item){return '<button type="button" class="choice" data-value="'+escapeHtml(item.id)+'"><span><b>'+escapeHtml(item.name)+'</b><small>'+Number(item.duration_minutes||30)+' dakika</small></span><strong>₺ '+Number(item.price||0).toLocaleString('tr-TR')+'</strong></button>'}).join('')||'<p class="muted">Aktif hizmet bulunamadı.</p>';q('employees').innerHTML=catalogue.employees.map(function(item){return '<button type="button" class="choice" data-value="'+escapeHtml(item.id)+'"><span><b>'+escapeHtml(item.full_name)+'</b><small>Çalışan seçimi</small></span></button>'}).join('')||'<p class="muted">Aktif çalışan bulunamadı.</p>';q('services').addEventListener('click',function(event){var button=event.target.closest('button');if(button)choose('services','serviceId',button.dataset.value)});q('employees').addEventListener('click',function(event){var button=event.target.closest('button');if(button)choose('employees','employeeId',button.dataset.value)})}
async function loadCatalogue(){try{catalogue=await json(API+'?action=catalogue',{cache:'no-store'});renderCatalogue()}catch(ex){q('services').innerHTML='<p class="error">'+escapeHtml(ex.message)+'</p>'}}
function show(next){step=next;document.querySelectorAll('.step').forEach(function(node){node.classList.toggle('active',Number(node.dataset.step)===step)});document.querySelectorAll('.steps span').forEach(function(node,index){node.classList.toggle('active',index<step)});q('backButton').hidden=step===1;q('nextButton').hidden=step===5;q('submitButton').hidden=step!==5;error('');window.scrollTo({top:q('bookingCard').offsetTop-12,behavior:'smooth'})}
async function loadSlots(){q('slots').innerHTML='<p class="loading">Müsait saatler kontrol ediliyor…</p>';try{var url=API+'?action=availability&date='+encodeURIComponent(state.date)+'&service='+encodeURIComponent(state.serviceId)+(state.employeeId?'&employee='+encodeURIComponent(state.employeeId):''),data=await json(url,{cache:'no-store'});q('slots').innerHTML=data.slots.map(function(item){return '<button type="button" class="slot" data-value="'+item.time+'">'+item.time+'</button>'}).join('')||'<p class="muted">Bu tarihte uygun saat bulunamadı.</p>';q('pendingHint').hidden=!data.slots.length;q('slots').onclick=function(event){var button=event.target.closest('button');if(button)choose('slots','time',button.dataset.value)}}catch(ex){q('slots').innerHTML='<p class="error">'+escapeHtml(ex.message)+'</p>'}}
function validate(){if(step===1&&!state.serviceId)return 'Bir hizmet seçin.';if(step===2&&!state.employeeId)return 'Bir çalışan seçin.';if(step===3&&!q('bookingDate').value)return 'Bir tarih seçin.';if(step===4&&!state.time)return 'Müsait bir saat seçin.';return ''}
function summary(){var s=service(),e=employee();q('summary').innerHTML='<p><b>Hizmet:</b> '+escapeHtml(s&&s.name)+'</p><p><b>Çalışan:</b> '+escapeHtml(e?e.full_name:'Fark etmez')+'</p><p><b>Tarih:</b> '+escapeHtml(state.date)+'</p><p><b>Saat:</b> '+escapeHtml(state.time)+'</p>'}
q('nextButton').onclick=async function(){var message=validate();if(message)return error(message);if(step===3){state.date=q('bookingDate').value;state.time='';await loadSlots()}if(step===4)summary();show(step+1)};
q('backButton').onclick=function(){show(Math.max(1,step-1))};
q('bookingDate').onchange=function(){state.date=this.value;state.time=''};
q('customerPhone').oninput=function(){var d=this.value.replace(/\D/g,'').slice(0,11);this.value=d.replace(/^(\d{4})(\d{3})(\d{2})(\d{0,2}).*/,function(_,a,b,c,e){return [a,b,c,e].filter(Boolean).join(' ')})};
q('bookingForm').onsubmit=async function(event){event.preventDefault();var name=q('customerName').value.trim(),phone=q('customerPhone').value;if(name.length<3)return error('Ad soyad bilgisini kontrol edin.');if(!/^0?5\d{9}$/.test(phone.replace(/\D/g,'')))return error('Telefon numarasını 05XX XXX XX XX biçiminde girin.');var button=q('submitButton');button.disabled=true;button.textContent='Gönderiliyor…';try{var data=await json(API+'?action=create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerName:name,customerPhone:phone,serviceId:state.serviceId,employeeId:state.employeeId||null,date:state.date,time:state.time,note:q('customerNote').value})});q('bookingCard').hidden=true;q('requestNumber').textContent=data.requestNumber;q('statusLink').href='durum/?token='+encodeURIComponent(data.statusToken);q('successCard').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}catch(ex){error(ex.message)}finally{button.disabled=false;button.textContent='Talebi gönder'}};
var today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Istanbul'}).format(new Date());q('bookingDate').min=today;q('bookingDate').max=new Date(Date.now()+90*86400000).toISOString().slice(0,10);loadCatalogue();
})();
