(function(){
  'use strict';
  var API='https://oxuwwjsakhcqimjsfris.supabase.co/functions/v1/customer-booking-request',q=function(id){return document.getElementById(id)},state=null,busy=false,loadId=0,token='',pendingOperation=null;
  async function json(url,options){var response=await fetch(url,Object.assign({cache:'no-store'},options)),data=await response.json();if(!response.ok)throw new Error(data.error||'Sunucuya ulaşılamadı.');return data}
  function localParts(value){var parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value)).split(' ');return {date:parts[0],time:parts[1]}}
  function message(value){q('message').textContent=value||''}
  function lock(value){busy=value;['check','update','cancel','date','time','confirmCancel'].forEach(function(id){q(id).disabled=value});if(!value)q('update').disabled=!q('time').value}
  async function check(){if(busy)return;token=q('token').value.trim();state=null;q('manage').hidden=true;q('result').hidden=false;q('result').textContent='Yükleniyor…';lock(true);try{var data=await json(API+'?action=status&token='+encodeURIComponent(token));state=data;var item=data.appointment;q('result').replaceChildren();var heading=document.createElement('h2');heading.textContent=({approved:'Randevunuz onaylandı',cancelled:'Randevunuz iptal edildi',pending:'Talebiniz inceleniyor',rejected:'Talebiniz onaylanamadı'})[data.status]||'Randevu durumu';q('result').append(heading);if(item){var detail=document.createElement('p');detail.textContent=item.customer+' · '+item.service+' · '+(item.employee||'')+' · '+new Date(item.scheduledAt).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})+' · '+item.amount+' TL';q('result').append(detail);var parts=localParts(item.scheduledAt);q('date').value=parts.date;q('date').min=localParts(new Date().toISOString()).date;q('manage').hidden=!item.canManage}message(item&&!item.canManage&&data.managementMessage?data.managementMessage:'')}catch(error){q('result').textContent=error.message}finally{lock(false)}if(state?.appointment?.canManage)await availability()}
  async function availability(){var request=++loadId,selectedToken=token,date=q('date').value;q('time').replaceChildren(new Option('Saatler yükleniyor…',''));q('update').disabled=true;if(!date)return;try{var data=await json(API+'?action=customer-availability&token='+encodeURIComponent(selectedToken)+'&date='+date);if(request!==loadId||selectedToken!==token)return;q('time').replaceChildren(new Option(data.slots.length?'Saat seçin':'Bu tarihte uygun saat yok',''));data.slots.forEach(function(slot){q('time').append(new Option(slot.time,slot.time))});message('')}catch(error){if(request===loadId)message(error.message)}}
  async function action(kind){if(busy||!state)return;var key=JSON.stringify([token,state.revision,kind,q('date').value,q('time').value]);if(!pendingOperation||pendingOperation.key!==key)pendingOperation={key:key,id:crypto.randomUUID()};lock(true);try{await json(API+'?action=customer-'+kind,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:token,operation:pendingOperation.id,revision:state.revision,date:q('date').value,time:q('time').value})});pendingOperation=null;q('cancelDialog').close();lock(false);await check();message(kind==='cancel'?'Randevunuz iptal edildi.':'Randevunuz güncellendi.')}catch(error){message(error.message)}finally{lock(false)}}
  q('check').onclick=check;q('date').onchange=availability;q('time').onchange=function(){q('update').disabled=!q('time').value};q('manage').onsubmit=function(event){event.preventDefault();if(q('time').value)action('update')};q('cancel').onclick=function(){q('cancelDialog').showModal()};q('keep').onclick=function(){q('cancelDialog').close()};q('confirmCancel').onclick=function(){action('cancel')};
  var initial=new URLSearchParams(location.search).get('token');if(initial){q('token').value=initial;check()}
})();
